//#define SH86278_TEST_EV

//#define LDO_1700mv
#define LDO_1900mv
#define BKLIGHT_HIGH_ON
#define SP_SD_DRIVER
#define PCB_WITH_SPEAKER
#define AVOID_POP_NOISE
//#define ICE_Ibuf_Cmd					  
//#define ICE_Mode						 	
												 
#define TARGET_BootBlock
//#define TARGET_PowerOn
//#define TARGET_PowerOff
//#define TARGET_MainMenu					   
//#define TARGET_System
//#define TARGET_Udisk
											
//#define TARGET_Music_0_Main
//#define TARGET_Music_1_Init
//#define TARGET_Music_2_Get_Id3
//#define TARGET_Music_3_Pro_Id3
//#define TARGET_Music_4_lrc
//#define TARGET_Music_5_Get_Item_Num					   
//#define TARGET_Music_6_Get_Item_Name
//#define TARGET_Music_7_SelFile
//#define TARGET_Music_8_Delete
//#define TARGET_Music_9_Fseek
//#define TARGET_Music_A_Save_Para				
//#define TARGET_Music_B_SubFunc
//#define TARGET_Music_C_SwitchCard
											  
//#define TARGET_Record_0_Main					
//#define TARGET_Record_1_Init1									 
//#define TARGET_Record_2_Init2					  
//#define TARGET_Record_3_Start_Sub
//#define TARGET_Record_4_Stop_Sub
//#define TARGET_Record_5_Save_Para
//#define TARGET_Record_6_Get_Next_File
//#define TARGET_Record_7_Dynamic_Display
//#define TARGET_Record_8_SwitchCard

//#define TARGET_Voice_0_Main
//#define TARGET_Voice_1_Init1
//#define TARGET_Voice_2_Init2						
//#define TARGET_Voice_3_Init_Play
//#define TARGET_Voice_4_Sel_File
//#define TARGET_Voice_5_Fseek							 
//#define TARGET_Voice_6_Del_File
//#define TARGET_Voice_7_Save_Para			
//#define TARGET_Voice_8_SwitchCard
														
//#define TARGET_FM_0_Main				   
//#define TARGET_FM_1_Restore_Para
//#define TARGET_FM_2_Save_Para
//#define TARGET_FM_3_DrvTea5767
//#define TARGET_FM_5_DrvAR1010
//#define TARGET_FM_6_DrvCL6017S
//#define TARGET_FM_7_DrvSI4702
//#define TARGET_FM_8_DrvRda5807SP
//#define TARGET_FM_9_DrvBK1080

//#define TARGET_Ebook_0_Main
//#define TARGET_Ebook_1_Init
//#define TARGET_Ebook_2_Init_Play
//#define TARGET_Ebook_3_Get_Page_Num
//#define TARGET_Ebook_4_Save_Para
//#define TARGET_Ebook_5_Del_File
//#define TARGET_Ebook_6_Get_Item_Num
//#define TARGET_Ebook_7_Get_Item_Name
//#define TARGET_Ebook_8_SwitchCard

//#define TARGET_Tel_0_Main
//#define TARGET_Tel_1_Del_Old_File
//#define TARGET_Tel_2_Import
//#define TARGET_Tel_3_Export
//#define TARGET_Tel_4_Check_Tel_File


#ifdef ICE_Mode

	#define READ_RAIT_DEF
	#define UI_COMMON_FUNC_DEF
 		#define UI_POWER_ON_BKLIGHT
		#define UI_POWER_OFF_BKLIGHT
	#define API_SFC_INTERFACE_INITPARA
	#define FILE_SYSTEM_FUNC_DEF_TEST
		#define FS_POWER_ON_BOOT_TEST
		#define FILE_SYSTEM_VAR_DEF
	#define	API_LCD_DRIVER_DEF
	#define LCD_DRIVER_DEF_TEST
		#define LCD_INIT_FUNC_TEST 

	#define LCD_API_DEF
		#define	API_LCD_DISPLAY_PICTURE
	   	#define FS_NOT_SD_DEF
#endif



#ifdef TARGET_BootBlock

	#define UI_BOOTBLOCK_DEFINE	
	#define UI_DIS_CODE_PIC
		#define	UI_DISPLAY_BLOCK_CODE_PIC
	#define UI_COMMON_FUNC_DEF
		#define UI_POWER_ON_BKLIGHT
		#define UI_POWER_OFF_BKLIGHT
	#define AP_BOOTBLOCK_DEF
	#define AP_BOOTBLOCK_VAR_DEF
	#define API_COMMON_FUNC_C_DEF
  		#define API_READ_SYS_PARA_TO_DBUF
  		#define	API_LCD_DRIVER_DEF
		#define	API_LCD_DRIVER_INIT_FUNC
		#define	API_LCD_OFF_FUNC	

		#define	AP_BOOTBLOCK_FM_STANDBY
		#define	AP_BOOTBLOCK_FM_COMMON_FUNC_DEF
		#define	AP_BOOTBLOCK_FM_VAR_DEF
	#define FILE_SYSTEM_FUNC_DEF
		#define FILE_SYSTEM_VAR_DEF
		#define FS_WRITE_EF_INTERFACE
/*
?C_C51STARTUP(0x76),?PR?*?START_MAIN,LOAD_FUNC,SFC_DRIVER_SUB,SFC_DRIVER_READ,SFC_DRIVER_CLRBUF_0XFF,SFC_DRIVER_SUB1,?PR?*?UI_BOOTBLOCK_PM1_START(0x1190),BOOTBLOCK_DISPLAY,?PR?*?UI_COMMON_FUNC,SFC_DRIVER_INIT,AP_BOOTBLOCK,?PR?*?AP_BOOTBLOCK_FM_STANDBY,?CO?UI_COMMON_FUNC,LCD_FUNC,?PR?API_READ_SYSPARA_TODBUF0?API_COMMON_FUNC,?CO?AP_BOOTBLOCK_FM_STANDBY,?C?LIB_CODE,?PR?AP_BOOTBLOCK_FM_STANDBY,SFC_DRIVER_CK_ID,DRV_FM_COMMON_SEG,SFC_DRIVER_WRITE_SUB,SFC_DRIVER_INIT_SUB

*/
#endif



#ifdef TARGET_PowerOn

	#define UI_POWERON_DEF
	#define UI_COMMON_FUNC_DEF
		#define UI_POWER_ON_BKLIGHT
	#define AP_POWERON_DEF
	#define AP_DYNAMICLOAD_POWERON_DEF	
	#define API_COMMON_FUNC_C_DEF
	   		#define API_READ_SYS_PARA_TO_DBUF
			#define API_DYNAMICLOAD_POWER_OFF	
	#define API_SFC_INTERFACE_INITPARA
 	#define	LCD_API_DEF
		#define API_LCD_DISPLAY_PICTURE
	#define	API_LCD_DRIVER_DEF
 	#define FILE_SYSTEM_FUNC_DEF
		#define FILE_SYSTEM_VAR_DEF
		#define FS_POWER_ON_BOOT
		#define FS_WRITE_EF_INTERFACE
	#define	ISR_POWER_ON_MODE

	#define MSI_INIT_DEF
/*
?C_C51STARTUP(0x76),?PR?*?START_MAIN,LOAD_FUNC,SFC_DRIVER_SUB,SFC_DRIVER_READ,SFC_DRIVER_CLRBUF_0XFF,SFC_DRIVER_SUB1,?PR?*?UI_POWERON(0x1190),ISR_POWER_ON_FUNC,?PR?*?UI_COMMON_FUNC,?PR?*?AP_POWERON,?PR?*?AP_POWERON_DYNAMICLOAD,API_SFC_INITPAR_FUNC,MSI_API_FUNC,?PR?API_DYNAMICLOAD_POWEROFF?API_COMMON_FUNC,API_SFC_WR_FUNC,SFC_DRIVER_WRITE,LCD_INTERFACE_FUNC,LCD_FUNC,?CO?UI_COMMON_FUNC,?PR?*?API_FS,?PR?API_READ_SYSPARA_TODBUF0?API_COMMON_FUNC,?CO?AP_POWERON,FS_BASIC_FUNC,?C?LIB_CODE,?PR?AP_POWERON
*/
#endif



#ifdef TARGET_PowerOff

  	#define UI_POWEROFF_DEF
   	#define UI_COMMON_FUNC_DEF
		#define UI_POWER_ON_BKLIGHT
	  	#define UI_POWER_OFF_BKLIGHT
	#define AP_POWEROFF_DEF
	#define	LCD_API_DEF
		#define API_LCD_DISPLAY_PICTURE
		#define API_LCD_CLR_ASSIGNED_AREA
	#define	API_LCD_DRIVER_DEF
		#define API_LCD_OFF_FUNC
	#define ISR_POWER_OFF_MODE

/*
?C_C51STARTUP(0x76),?PR?*?START_MAIN,LOAD_FUNC,SFC_DRIVER_SUB,SFC_DRIVER_READ,SFC_DRIVER_CLRBUF_0XFF,SFC_DRIVER_SUB1,?PR?*?UI_POWEROFF(0x1190),ISR_POWER_OFF_FUNC,?PR?*?AP_POWEROFF,LCD_INTERFACE_FUNC,LCD_FUNC,?CO?UI_COMMON_FUNC,?PR?UI_POWERON_BACKLIGHT?UI_COMMON_FUNC,?PR?UI_POWEROFF_BACKLIGHT?UI_COMMON_FUNC,?PR?UI_POWEROFF
*/
#endif



#ifdef TARGET_MainMenu	 

	#define	UI_MAINMENU_DEF
	#define UI_MAINMENU_INIT_DEF
	#define UI_MAINMENU_PROCESS_DEF
	#define UI_MAINMENU_VAR_DEF
   	#define UI_COMMON_FUNC_DEF
		#define UI_PROCESS_EVT_BAT_SUB
		#define UI_POWER_ON_BKLIGHT
		#define UI_POWER_OFF_BKLIGHT
   	#define AP_DYNAMICLOAD_ALL_MODE_DEF
	#define AP_MAINMENU_PROCESS_DEF
	#define API_COMMON_FUNC_C_DEF
		#define API_CHECK_SLEEP_POWEROFF
		#define API_CHECK_IDLE_POWEROFF
		#define API_CHECK_BAT_DETECT
		#define API_CHECK_BKLIGHT_OFF
		#define API_KEY_MAPPING
		#define API_READ_SYS_PARA_TO_DBUF
 	#define API_COMMON_FUNC_C_DEF
 	#define	LCD_API_DEF
		#define API_LCD_DISPLAY_PICTURE
	#define	API_LCD_DRIVER_DEF	
 	#define FILE_SYSTEM_FUNC_DEF
		#define FILE_SYSTEM_VAR_DEF
		#define FS_WRITE_EF_INTERFACE

   	#define ISR_MAINMENU_FUNC_DEF


/*
?C_C51STARTUP(0x76),?PR?*?START_MAIN,LOAD_FUNC,SFC_DRIVER_SUB,SFC_DRIVER_READ,SFC_DRIVER_CLRBUF_0XFF,SFC_DRIVER_SUB1,?PR?*?UI_MAINMENU(0x1190),?PR?*?UI_MAINMENU_INIT,?PR?*?UI_MAINMENU_PROCESS_EVENT,?PR?*?UI_COMMON_FUNC,?PR?*?AP_MAINMENU_DYNAMICLOAD,?PR?*?AP_MAINMENU_PROCESS_EVENT,API_SFC_INITPAR_FUNC,API_SFC_WR_FUNC,SFC_DRIVER_WRITE,MAIN_MENU_FUNC,LCD_INTERFACE_FUNC,LCD_FUNC,?C?LIB_CODE,FS_BASIC_FUNC,?PR?API_CHECK_IDLE_POWEROFF?API_COMMON_FUNC,?PR?API_CHECK_BKLIGHTOFF?API_COMMON_FUNC,?PR?API_KEY_MAPPING?API_COMMON_FUNC,?PR?API_CHECK_SLEEP_POWEROFF?API_COMMON_FUNC,?PR?API_CHECK_BATTERY?API_COMMON_FUNC,?CO?UI_COMMON_FUNC,?PR?API_READ_SYSPARA_TODBUF0?API_COMMON_FUNC,?PR?API_COMMON_FUNC
*/
#endif



#ifdef TARGET_System
	#define UI_SYS_MAIN_DEF
   	#define UI_SYS_KEY_DEF
	#define UI_SYS_DISPLAY_DEF
	#define UI_SYS_TIMER_DEF
	#define UI_SYS_VAR_DEF
 	#define UI_COMMON_FUNC_DEF
		#define UI_CHECK_REFRESH_MENU_FLAG
   		#define UI_PROCESS_EVT_BAT_SUB
	   	#define UI_POWER_ON_BKLIGHT
		#define UI_POWER_OFF_BKLIGHT
	#define AP_SYSTEM_INIT_DEF
	#define AP_SYSTEM_ENHANCE_DEF
	#define API_COMMON_FUNC_C_DEF
		#define FS_POWER_ON_BOOT
		#define API_CHECK_SLEEP_POWEROFF
		#define API_CHECK_IDLE_POWEROFF
		#define API_CHECK_BAT_DETECT
		#define API_CHECK_BKLIGHT_OFF
		#define API_KEY_MAPPING
		#define API_READ_SYS_PARA_TO_DBUF
		#define API_DYNAMICLOAD_USB
		#define API_DYNAMICLOAD_POWER_OFF
		#define API_DYNAMICLOAD_MAIN_MENU
	#define	LCD_API_DEF
		#define API_LCD_REVERSE_DISPLAY
		#define API_LCD_DISPLAY_PICTURE
		#define API_LCD_DISPLAY_8x6ZIKU
		#define API_LCD_DISPLAY_UNICODE
		#define API_DISPLAY_REVERSE_DEFINE
	#define	API_LCD_DRIVER_DEF
	#define FILE_SYSTEM_FUNC_DEF
		#define FILE_SYSTEM_VAR_DEF
		#define FS_GET_FREE_SPACE_DEF
		#define FS_WRITE_EF_INTERFACE
		#define FS_NF_FAT_ANALYZE
		#define FS_ANALYZE_BUF
	#define ISR_SYS_FUNC_DEF
#define FS_NOT_SD_DEF

/*	
?C_C51STARTUP(0x76),?PR?*?START_MAIN,LOAD_FUNC,SFC_DRIVER_SUB,SFC_DRIVER_READ,SFC_DRIVER_CLRBUF_0XFF,SFC_DRIVER_SUB1,?PR?*?UI_SYS_MAIN(0x1190),?PR?*?UI_SYS_KEY,?CO?UI_SYS_KEY,?PR?*?UI_SYS_DISPLAY,?CO?UI_SYS_DISPLAY,?PR?*?UI_SYS_PROCESS_TIMER,?PR?*?UI_COMMON_FUNC,?CO?UI_COMMON_FUNC,?PR?*?AP_SYS_INIT,?PR?*?AP_SYS_ENHANCE,SFC_DRIVER_WRITE,?PR?*?API_COMMON_FUNC,?C?LIB_CODE,?PR?*?API_FS,FS_BASIC_FUNC,LCD_INTERFACE_FUNC,LCD_FUNC, API_SFC_INITPAR_FUNC,ISR_SYS_FUNC,?PR?API_COMMON_FUNC,?PR?UI_SYS_DISPLAY,?PR?UI_SYS_KEY
*/
#endif




#ifdef TARGET_Udisk
	#define UI_UDISK_MAIN
	#define UI_UDISK_PROCESS_DEF
	#define UI_UDISK_VAR_DEF
	#define UI_COMMON_FUNC_DEF
		#define UI_POWER_ON_BKLIGHT
		#define UI_PROCESS_EVT_BAT_SUB
		#define UI_POWER_OFF_BKLIGHT
	#define API_COMMON_FUNC_C_DEF
		#define UI_DIS_BATTERY_PIC
		#define API_CHECK_BAT_DETECT
		#define API_CHECK_BKLIGHT_OFF
	#define	LCD_API_DEF
		#define API_LCD_DISPLAY_PICTURE
	#define ISR_USB_FUNC_DEF

	#define	API_LCD_DRIVER_DEF
		#define MSI_SUPPORT_USB_DEF

/*
?C_C51STARTUP(0x76),?PR?*?START_MAIN,LOAD_FUNC,SFC_DRIVER_SUB,SFC_DRIVER_READ,SFC_DRIVER_CLRBUF_0XFF,SFC_DRIVER_SUB1,?PR?*?UI_UDISK_MAIN(0x1190),ISR_USB_FUNC,UDISK_SUB,?PR?*?UI_UDISK_PROCESS_EVENT,?PR?*?UI_COMMON_FUNC,?PR?API_CHECK_BKLIGHTOFF?API_COMMON_FUNC,?PR?API_CHECK_BATTERY?API_COMMON_FUNC,?CO?UI_COMMON_FUNC,LCD_INTERFACE_FUNC,LCD_FUNC,?C?LIB_CODE,SFC_DRIVER_WRITE,MSI_DRIVER_FUNC(0x3000),MSI_API_FUNC
*/
#endif



#ifdef TARGET_Music_0_Main

	#define UI_MUSIC_MAIN_DEF
	#define	UI_MUSIC_VAR_DEF
	#define UI_MUSIC_PROCESS_KEY_DEF
	#define UI_MUSIC_PROCESS_TIMER_DEF
	#define UI_MUSIC_PROCESS_KEY_DEF
	#define UI_MUSIC_PROCESS_DISPLAY_DEF
	#define UI_COMMON_FUNC_DEF
	   	#define UI_PROCESS_EVT_BAT_SUB
	   	#define UI_CHECK_REFRESH_MENU_FLAG
		#define UI_POWER_ON_BKLIGHT
		#define UI_POWER_OFF_BKLIGHT
		#define UI_DIS_BATTERY_PIC
	#define AP_MUSIC_PROCESS_DEF
	#define AP_MUSIC_COMMON_FUNC_DEF
		#define AP_ENABLE_DAC_DEF
		#define MUSIC_GET_BITRATE_DEF
	#define AP_MUSIC_BASAL_DEF
 	#define	API_COMMON_FUNC_C_DEF
	   	#define API_SYS_ENABLE_AUDIO_DEC_DEF
	   	#define API_DETECT_HEADPHONE_PLUG_DEF
	   	//#define API_CHECK_SLEEP_POWEROFF
		//#define API_CHECK_IDLE_POWEROFF
		#define API_CHECK_BAT_DETECT
		#define API_CHECK_BKLIGHT_OFF
		#define API_KEY_MAPPING
		#define API_DYNAMICLOAD_USB	
		#define API_DYNAMICLOAD_POWER_OFF
		#define API_DYNAMICLOAD_MAIN_MENU
   	#define API_COMMON_FUNC_ASM_DEF
		#define API_SET_VOLUME_DEF
	#define API_COMMUNICANT_COMMAND_DEF
		#define API_CMD_START_DEC
		#define API_CMD_CONTROL_DEC
		#define API_CMD_RESET_DEC
		#define API_CMD_DEC_MP3_DEADER
		#define API_CMD_SET_EQ
		#define API_CMD_SET_FREQ_FADE
		#define API_CMD_FILL_OR_DIS_DBUF_OVER
		#define CMD_API_RW_MPEG_REG

  	#define API_DYNAMICLOAD_TARGET_DEF
		#define API_DYNAMICLOAD_MUSIC_TARGET
	#define FILE_SYSTEM_FUNC_DEF
		#define FILE_SYSTEM_VAR_DEF
		#define FS_FREAD_DEF
	#define	LCD_API_DEF
		#define API_LCD_DISPLAY_PICTURE
		#define API_LCD_DISPLAY_UNICODE
		#define API_LCD_DISPLAY_8x6ZIKU
		#define API_DISPLAY_REVERSE_DEFINE
		#define API_LCD_REVERSE_DISPLAY
		#define API_AUDIO_FILL_DBUF_EVENT
	#define	API_LCD_DRIVER_DEF
   	#define ISR_MUSIC_FUNC_DEF

	#define MSI_SUPPORT_DEF
	
	#define AVOID_POP_NOISE

	#define SP_PLAY_RESERVEDMP3_DEF

	#define RTC_I2C_DRIVER_DEF
	#define RTC_I2C_API_DEF
	#define RTC_I2C_INIT_DEF
	#define RTC_I2C_API_READ_DEF
	#define RTC_I2C_API_SET_DEF

/*
?C_C51STARTUP(0x76),?PR?*?START_MAIN,LOAD_FUNC,SFC_DRIVER_SUB,SFC_DRIVER_READ,SFC_DRIVER_CLRBUF_0XFF,SFC_DRIVER_SUB1,?PR?*?UI_MUSIC_MAIN(0x1190),DYNAMIC_FUNC_SEG,ISR_MUSIC_FUNC,API_COMMUNICANT_CMD,?PR?*?UI_MUSIC_PROCESS_KEY,?PR?*?AP_MUSIC_BASAL,?PR?AP_MUSIC_BASAL,?PR?*?UI_MUSIC_PROCESS_DISPLAY,?PR?*?AP_MUSIC_PROCESS_EVENT,?PR?*?UI_MUSIC_PROCESS_TIMER,COM_FUNC_SEG,?PR?*?UI_COMMON_FUNC,?CO?UI_COMMON_FUNC,?PR?AP_MUSIC_PROCESS_EVENT,FS_BASIC_FUNC,?PR?API_COMMON_FUNC,?PR?*?API_COMMON_FUNC,MSI_DRIVER_FUNC(0x3000),MSI_API_FUNC,?PR?*?API_FS,LCD_INTERFACE_FUNC,LCD_FUNC,?CO?UI_MUSIC_PROCESS_DISPLAY,?PR?AP_ENABLE_DAC?AP_MUSIC_COMMON_FUNC,?CO?AP_MUSIC_COMMON_FUNC,?PR?AP_GET_BITRATE?AP_MUSIC_COMMON_FUNC,?C?LIB_CODE,?PR?UI_MUSIC_PROCESS_KEY,?PR?UI_MUSIC_PROCESS_DISPLAY,?PR?UI_MUSIC_PROCESS_TIMER
*/
#endif


#ifdef TARGET_Music_1_Init
	#define	UI_MUSIC_VAR_DEF
	#define AP_MUSIC_INIT_DEF
	#define AP_MUSIC_COMMON_FUNC_DEF
		#define AP_ENABLE_DAC_DEF
	#define API_COMMON_FUNC_C_DEF
		#define API_READ_SYS_PARA_TO_DBUF
	#define API_COMMON_FUNC_ASM_DEF
		#define API_SET_VOLUME_DEF
	
	#define FILE_SYSTEM_FUNC_DEF
		#define FILE_SYSTEM_VAR_DEF
		#define FS_ENTER_DIR_DEF
		#define FS_EXIT_DIR_DEF
		#define FS_GET_ITEM_NUM_DEF
		#define FS_GET_FILEPATH_DEF
		#define FS_ENTER_ROOT_DEF
		#define FS_ENTER_APPOINTED_DIR_DEF
		#define FS_FOPEN_APPOINTED_DEF
		#define FS_FOPEN_DEF
		#define FS_CHECK_FILE_TYPE
			#define MSI_SUPPORT_DEF
			
	#define AVOID_POP_NOISE

	#define SP_PLAY_RESERVEDMP3_DEF
	#define	SP_PLAY_RSV_INIT
/*
?C_C51STARTUP(0x76),?PR?*?START_MAIN,LOAD_FUNC,SFC_DRIVER_SUB,SFC_DRIVER_READ,SFC_DRIVER_CLRBUF_0XFF,SFC_DRIVER_SUB1,?PR?*?AP_MUSIC_INIT(0x1C00),?PR?*?API_COMMON_FUNC,COM_FUNC_SEG,?PR?*?API_FS,FS_BASIC_FUNC,?PR?*?API_FS_SUB,?PR?AP_ENABLE_DAC?AP_MUSIC_COMMON_FUNC,?C?LIB_CODE,?PR?API_FS_SUB,?PR?API_FS,?PR?AP_MUSIC_INIT,MSI_DRIVER_FUNC(0x3000),MSI_API_FUNC
*/
#endif


#ifdef TARGET_Music_2_Get_Id3
	#define	UI_MUSIC_VAR_DEF
	#define AP_MUSIC_ID3_PROCESS_DEF
		#define AP_GET_MP3_ID3_DEF	
	#define API_COMMON_FUNC_ASM_DEF
		#define API_MERGE_4BYTE_DEF
	#define FILE_SYSTEM_FUNC_DEF
		#define FILE_SYSTEM_VAR_DEF
		#define FS_FREAD_DEF
		#define FS_FSEEK_DEF
			#define MSI_SUPPORT_DEF
/*
?C_C51STARTUP(0x76),?PR?*?START_MAIN,LOAD_FUNC,SFC_DRIVER_SUB,SFC_DRIVER_READ,SFC_DRIVER_CLRBUF_0XFF,SFC_DRIVER_SUB1,?PR?*?AP_MUSIC_ID3(0x1C00),?PR?*?API_FS,FS_BASIC_FUNC,?C?LIB_CODE,COM_FUNC_SEG,?PR?AP_MUSIC_ID3,MSI_DRIVER_FUNC(0x3000),MSI_API_FUNC
*/
#endif


#ifdef TARGET_Music_3_Pro_Id3
	#define	UI_MUSIC_VAR_DEF
	#define AP_MUSIC_ID3_PROCESS_DEF
		#define AP_PROCESS_ID3_DEF
	#define API_COMMON_FUNC_ASM_DEF
		#define API_CONVERT_ISN_UNICODE
		#define API_EXCHANGE_BYTE_DEF
		#define API_MERGE_2BYTE_DEF
			#define MSI_SUPPORT_DEF


/*	   
?C_C51STARTUP(0x76),?PR?*?START_MAIN,LOAD_FUNC,SFC_DRIVER_SUB,SFC_DRIVER_READ,SFC_DRIVER_CLRBUF_0XFF,SFC_DRIVER_SUB1,?PR?*?AP_MUSIC_ID3(0x1C00),?C?LIB_CODE,COM_FUNC_SEG,?PR?AP_MUSIC_ID3

?C_C51STARTUP(0x76),?PR?*?START_MAIN,LOAD_FUNC,SFC_DRIVER_SUB,SFC_DRIVER_READ,SFC_DRIVER_CLRBUF_0XFF,SFC_DRIVER_SUB1,?PR?*?AP_MUSIC_ID3(0x1C00),?C?LIB_CODE,COM_FUNC_SEG,?PR?AP_MUSIC_ID3,MSI_DRIVER_FUNC(0x3000),MSI_API_FUNC
*/
#endif


#ifdef TARGET_Music_4_lrc
	#define	UI_MUSIC_VAR_DEF
	#define AP_MUSIC_LRC_PROCESS_DEF
		#define AP_GET_LRC_FILE_DATA
	#define API_COMMON_FUNC_ASM_DEF
		#define API_CONVERT_ISN_UNICODE
		#define API_MERGE_4BYTE_DEF
		#define API_MERGE_2BYTE_DEF
  	#define FILE_SYSTEM_FUNC_DEF
		#define FILE_SYSTEM_VAR_DEF
		#define FS_FREAD_DEF
		#define FS_FSEEK_DEF
		#define FS_WRITE_EF_INTERFACE

			#define MSI_SUPPORT_DEF
/*
?C_C51STARTUP(0x76),?PR?*?START_MAIN,LOAD_FUNC,SFC_DRIVER_SUB,SFC_DRIVER_READ,SFC_DRIVER_CLRBUF_0XFF,SFC_DRIVER_SUB1,?PR?*?AP_MUSIC_LRC(0x1C00),API_SFC_INITPAR_FUNC,API_SFC_WR_FUNC,COM_FUNC_SEG,?PR?*?API_FS,FS_BASIC_FUNC,?C?LIB_CODE,SFC_DRIVER_WRITE,?PR?AP_MUSIC_LRC,MSI_DRIVER_FUNC(0x3000),MSI_API_FUNC
*/
#endif


#ifdef TARGET_Music_5_Get_Item_Num
	#define	UI_MUSIC_VAR_DEF
	#define AP_MUSIC_GET_ITEM_NUM
	#define FB_GET_ITEM_NUM_DEF
	#define FILE_SYSTEM_FUNC_DEF
		#define FILE_SYSTEM_VAR_DEF
		#define FS_GET_ITEM_NUM_DEF
		#define FS_ENTER_DIR_DEF
		#define FS_EXIT_DIR_DEF

			#define MSI_SUPPORT_DEF
/*
?C_C51STARTUP(0x76),?PR?*?START_MAIN,LOAD_FUNC,SFC_DRIVER_SUB,SFC_DRIVER_READ,SFC_DRIVER_CLRBUF_0XFF,SFC_DRIVER_SUB1,?PR?*?FB_GET_ITEM_NUM(0x1C00),?PR?*?API_FS,?PR?*?API_FS_SUB,FS_BASIC_FUNC,?C?LIB_CODE,?PR?API_FS_SUB,MSI_DRIVER_FUNC(0x3000),MSI_API_FUNC
*/
#endif


#ifdef TARGET_Music_6_Get_Item_Name
	#define	UI_MUSIC_VAR_DEF
	#define AP_MUSIC_GET_ITEM_NAME
	#define FB_GET_ITEM_NAME_DEF
	#define AP_MUSIC_LRC_PROCESS_DEF
		#define AP_CHECK_LRC_FILE_EXIST
	#define API_COMMON_FUNC_ASM_DEF
		#define API_CONVERT_ISN_UNICODE
		#define API_MERGE_2BYTE_DEF
	#define FILE_SYSTEM_FUNC_DEF
		#define FILE_SYSTEM_VAR_DEF
		#define FS_GET_83_NAME_DEF
		#define FS_GET_LONG_NAME_DEF
		#define FS_OPEN_DIR_DEF
		#define FS_FOPEN_APPOINTED_DEF
		#define FS_CHECK_FILE_TYPE
		#define FS_FOPEN_DEF
		#define FS_EXIT_DIR_DEF
		#define FS_GET_NEXT_FILE_INDIR_DEF
		#define FS_INIT_OPEN_VAR_DEF
		#define FS_ENTER_DIR_DEF

			#define MSI_SUPPORT_DEF
/*
?C_C51STARTUP(0x76),?PR?*?START_MAIN,LOAD_FUNC,SFC_DRIVER_SUB,SFC_DRIVER_READ,SFC_DRIVER_CLRBUF_0XFF,SFC_DRIVER_SUB1,?PR?*?FB_GET_ITEM_NAME(0x1C00),?PR?*?AP_MUSIC_LRC,?PR?*?API_FS,?PR?*?API_FS_SUB,FS_BASIC_FUNC,COM_FUNC_SEG,?C?LIB_CODE,?PR?API_FS_SUB,?PR?API_FS,?PR?AP_MUSIC_LRC,MSI_DRIVER_FUNC(0x3000),MSI_API_FUNC
*/
#endif


#ifdef TARGET_Music_7_SelFile
	#define	UI_MUSIC_VAR_DEF
	#define AP_MUSIC_SELECT_FILE_DEF

	#define FILE_SYSTEM_FUNC_DEF
		#define FILE_SYSTEM_VAR_DEF
		#define FS_ENTER_DIR_DEF
		#define FS_EXIT_DIR_DEF
		#define FS_GET_ITEM_NUM_DEF
		#define FS_ENTER_ROOT_DEF
		#define FS_GET_NEXT_FILE_INDIR_DEF
		#define FS_FOPEN_DEF
		#define FS_FOPEN_APPOINTED_DEF
		#define FS_CHECK_FILE_TYPE

		#define FS_OPEN_DIR_DEF
		#define FS_GET_LONG_NAME_DEF
		#define FS_GET_83_NAME_DEF

			#define MSI_SUPPORT_DEF
/*
?C_C51STARTUP(0x76),?PR?*?START_MAIN,LOAD_FUNC,SFC_DRIVER_SUB,SFC_DRIVER_READ,SFC_DRIVER_CLRBUF_0XFF,SFC_DRIVER_SUB1,?PR?*?AP_MUSIC_SEL_FILE(0x1C00),?PR?*?API_FS,?PR?*?API_FS_SUB,FS_BASIC_FUNC,?PR?RAND?RAND,?C?LIB_CODE,?PR?API_FS_SUB,?PR?API_FS,?PR?AP_MUSIC_SEL_FILE,MSI_DRIVER_FUNC(0x3000),MSI_API_FUNC
*/
#endif


#ifdef TARGET_Music_8_Delete
	#define	UI_MUSIC_VAR_DEF
	#define AP_MUSIC_DELETE_FILE
	#define FB_DELETE_FILE_DEF
	#define FILE_SYSTEM_FUNC_DEF
		#define FILE_SYSTEM_VAR_DEF
		#define FS_FOPEN_APPOINTED_DEF
		#define FS_INIT_OPEN_VAR_DEF
		#define FS_DELETE_DEF

			#define MSI_SUPPORT_DEF
/*
?C_C51STARTUP(0x76),?PR?*?START_MAIN,LOAD_FUNC,SFC_DRIVER_SUB,SFC_DRIVER_READ,SFC_DRIVER_CLRBUF_0XFF,SFC_DRIVER_SUB1,?PR?*?FB_DELETE_FILE(0x1C00),API_SFC_INITPAR_FUNC,API_SFC_WR_FUNC,?PR?*?API_FS,FS_BASIC_FUNC,SFC_DRIVER_WRITE,?PR?DIR_FLAG_ADDR?API_FS_SUB,?PR?_GET_ITEM_INDEX?API_FS_SUB,?C?LIB_CODE,?PR?API_FS_SUB,?PR?FB_DELETE_FILE,MSI_DRIVER_FUNC(0x3000),MSI_API_FUNC
*/
#endif


#ifdef TARGET_Music_9_Fseek
	#define	UI_MUSIC_VAR_DEF
	#define AP_MUSIC_FSEEK_DEF_DEF

	#define FILE_SYSTEM_FUNC_DEF
		#define FILE_SYSTEM_VAR_DEF
		#define FS_FSEEK_DEF
		#define FS_FREAD_DEF

			#define MSI_SUPPORT_DEF
/*
?C_C51STARTUP(0x76),?PR?*?START_MAIN,LOAD_FUNC,SFC_DRIVER_SUB,SFC_DRIVER_READ,SFC_DRIVER_CLRBUF_0XFF,SFC_DRIVER_SUB1,?PR?*?AP_MUSIC_FSEEK(0x1C00),?PR?*?API_FS,FS_BASIC_FUNC,?C?LIB_CODE,?PR?AP_MUSIC_FSEEK,MSI_DRIVER_FUNC(0x3000),MSI_API_FUNC
*/
#endif


#ifdef TARGET_Music_A_Save_Para
	#define	UI_MUSIC_VAR_DEF
	#define AP_MUSIC_SAVE_PARA_DEF

	#define FILE_SYSTEM_FUNC_DEF
		#define FILE_SYSTEM_VAR_DEF
		#define FS_WRITE_EF_INTERFACE

			#define MSI_SUPPORT_DEF
/*
?C_C51STARTUP(0x76),?PR?*?START_MAIN,LOAD_FUNC,SFC_DRIVER_SUB,SFC_DRIVER_READ,SFC_DRIVER_CLRBUF_0XFF,SFC_DRIVER_SUB1,?PR?*?AP_MUSIC_SAVE_PARA(0x1C00),SFC_DRIVER_WRITE,API_SFC_INITPAR_FUNC,API_SFC_WR_FUNC,FS_BASIC_FUNC,?C?LIB_CODE,?PR?AP_MUSIC_SAVE_PARA,MSI_DRIVER_FUNC(0x3000),MSI_API_FUNC
*/
#endif


#ifdef TARGET_Music_B_SubFunc
	#define	UI_MUSIC_VAR_DEF
	#define AP_MUSIC_SUBFUNC_DLOAD_DEF
	#define AP_MUSIC_COMMON_FUNC_DEF
		#define MUSIC_GET_SAMPLERATE_DEF
		#define MUSIC_GET_BITRATE_DEF

	#define FILE_SYSTEM_VAR_DEF

		#define MSI_SUPPORT_DEF
#endif
/*
?C_C51STARTUP(0x76),?PR?*?START_MAIN,LOAD_FUNC,SFC_DRIVER_SUB,SFC_DRIVER_READ,SFC_DRIVER_CLRBUF_0XFF,SFC_DRIVER_SUB1,?PR?*?AP_MUSIC_SUBFUNC_DLOAD(0x1C00),?PR?AP_GET_SAMPLERATE?AP_MUSIC_COMMON_FUNC,?CO?AP_MUSIC_COMMON_FUNC,?PR?AP_GET_BITRATE?AP_MUSIC_COMMON_FUNC,?C?LIB_CODE,?PR?AP_MUSIC_SUBFUNC_DLOAD,?PR?AP_MUSIC_COMMON_FUNC,MSI_DRIVER_FUNC(0x3000),MSI_API_FUNC
*/

#ifdef TARGET_Music_C_SwitchCard
	#define UI_MUSIC_VAR_DEF
	#define FB_SWITCH_CARD_DEF

	#define API_COMMON_FUNC_C_DEF
		#define API_DYNAMICLOAD_POWER_OFF

	#define FILE_SYSTEM_FUNC_DEF
		#define FILE_SYSTEM_VAR_DEF
		#define FS_POWER_ON_BOOT	
	//#define FS_ENTER_DIR_DEF
	//	#define FS_EXIT_DIR_DEF
		#define FS_GET_ITEM_NUM_DEF	
	//	#define FS_GET_FILEPATH_DEF
		#define FS_ENTER_ROOT_DEF
	//	#define FS_ENTER_APPOINTED_DIR_DEF
	//	#define FS_FOPEN_APPOINTED_DEF
	//	#define FS_FOPEN_DEF
	//	#define FS_CHECK_FILE_TYPE
		#define FS_INIT_OPEN_VAR_DEF				

	#define MSI_SUPPORT_DEF
#endif
/*
?C_C51STARTUP(0x76),?PR?*?START_MAIN,LOAD_FUNC,SFC_DRIVER_SUB,SFC_DRIVER_READ,SFC_DRIVER_CLRBUF_0XFF,SFC_DRIVER_SUB1,?PR?*?FB_SWITCH_CARD(0x1C00),?PR?*?API_COMMON_FUNC,?PR?*?API_FS,?PR?*?API_FS_SUB,FS_BASIC_FUNC,?C?LIB_CODE,?PR?API_FS,?PR?API_FS_SUB,MSI_DRIVER_FUNC(0x3000),MSI_API_FUNC
*/
/*
?C_C51STARTUP(0x76),?PR?*?START_MAIN,LOAD_FUNC,SFC_DRIVER_SUB,SFC_DRIVER_READ,SFC_DRIVER_CLRBUF_0XFF,SFC_DRIVER_SUB1,?PR?*?FB_SWITCH_CARD(0x1C00),?PR?*?API_COMMON_FUNC,?PR?*?API_FS,?PR?API_FS_SUB,?PR?DIR_FLAG_ADDR?API_FS_SUB,FS_BASIC_FUNC,?C?LIB_CODE,MSI_DRIVER_FUNC(0x3000),MSI_API_FUNC
*/



#ifdef TARGET_Record_0_Main
	#define UI_RECORD_VAR_DEF
	#define UI_RECORD_MAIN_DEF
	#define UI_RECORD_KEY_PROCESS_DEF
	#define UI_RECORD_DISPLAY_DEF
	#define UI_RECORD_PROCESS_TIMER_DEF
	#define UI_COMMON_FUNC_DEF
  		#define UI_PROCESS_EVT_BAT_SUB
	   	#define UI_POWER_ON_BKLIGHT
		#define UI_POWER_OFF_BKLIGHT
		#define UI_DIS_BATTERY_PIC
		#define UI_CHECK_REFRESH_MENU_FLAG
	#define AP_REC_BASAL_DEF
	#define AP_REC_PROCESS_DEF
	#define AP_RECORD_ENCODE_LIB_DEF
	#define API_COMMON_FUNC_C_DEF
		#define API_CHECK_SLEEP_POWEROFF
		#define API_CHECK_IDLE_POWEROFF
		#define API_CHECK_BAT_DETECT
		#define API_CHECK_BKLIGHT_OFF
		#define API_KEY_MAPPING
		#define API_DYNAMICLOAD_USB
		#define API_DYNAMICLOAD_POWER_OFF
		#define API_DYNAMICLOAD_MAIN_MENU
		#define API_READ_SYS_PARA_TO_DBUF

	#define API_DYNAMICLOAD_TARGET_DEF
		#define API_DYNAMICLOAD_REC_TARGET
		#define API_DYNAMICLOAD_FM_TARGET_3K
	#define	LCD_API_DEF
		#define API_LCD_DISPLAY_PICTURE
		#define API_LCD_DISPLAY_UNICODE
		#define API_LCD_DISPLAY_8x6ZIKU
		#define API_LCD_CLR_ASSIGNED_AREA
		#define API_DISPLAY_REVERSE_DEFINE
		#define API_LCD_REVERSE_DISPLAY
		#define FS_GET_VOICE_DIR_DEF
	#define ISR_RECORD_FUNC_DEF
	#define FILE_SYSTEM_FUNC_DEF
		#define FILE_SYSTEM_VAR_DEF
		#define FS_FWRITE_DEF
	#define	FS_WRITE_EF_INTERFACE
	#define	API_LCD_DRIVER_DEF

	    #define  MSI_SUPPORT_DEF
																																																																																																																																																																	  
/*	  
?C_C51STARTUP(0x76),?PR?*?START_MAIN,LOAD_FUNC,SFC_DRIVER_SUB,SFC_DRIVER_READ,SFC_DRIVER_CLRBUF_0XFF,SFC_DRIVER_SUB1,?PR?*?UI_REC_MAIN(0x1190),DYNAMIC_FUNC_SEG,ISR_RECORD_FUNC,?PR?*?UI_REC_KEY,?PR?*?AP_REC_BASAL,?PR?*?AP_REC_PROCESS_EVENT,?PR?*?API_COMMON_FUNC,?C?LIB_CODE,ADPCM_ENC_SEG,?PR?*?UI_REC_PROCESS_TIMER,?PR?*?UI_REC_DISPLAY,FS_BASIC_FUNC,MSI_DRIVER_FUNC(0x3000),MSI_API_FUNC,?CO?UI_COMMON_FUNC,SFC_DRIVER_WRITE,?PR?UI_DISPLAY_BATTERY?UI_COMMON_FUNC, ?PR?UI_POWEROFF_BACKLIGHT?UI_COMMON_FUNC,?PR?UI_POWERON_BACKLIGHT?UI_COMMON_FUNC,?PR?*?API_FS,LCD_FUNC,API_SFC_INITPAR_FUNC,?PR?UI_GET_BATLEVEL?UI_COMMON_FUNC,?PR?UI_PROCESSEVT_BATSUB?UI_COMMON_FUNC,?PR?API_COMMON_FUNC,?PR?UI_REC_DISPLAY,?PR?AP_REC_BASAL,?PR?UI_CHECK_REFRESH_MENUFLAG?UI_COMMON_FUNC
*/
#endif


#ifdef	TARGET_Record_1_Init1

   	#define UI_RECORD_VAR_DEF
   	#define AP_RECORD_INIT1_DEF
	#define API_COMMON_FUNC_C_DEF
		#define API_READ_SYS_PARA_TO_DBUF
   	#define FILE_SYSTEM_FUNC_DEF
		#define FILE_SYSTEM_VAR_DEF
			#define FS_GET_VOICE_DIR_DEF

			#define MSI_SUPPORT_DEF
/*
?C_C51STARTUP(0x76),?PR?*?START_MAIN,LOAD_FUNC,SFC_DRIVER_SUB,SFC_DRIVER_READ,SFC_DRIVER_CLRBUF_0XFF,SFC_DRIVER_SUB1,?PR?*?AP_REC_INIT1(0x1C00),SFC_DRIVER_WRITE,API_SFC_WR_FUNC,API_SFC_INITPAR_FUNC,FS_BASIC_FUNC,?PR?*?API_FS,?C?LIB_CODE,?PR?API_READ_SYSPARA_TODBUF0?API_COMMON_FUNC,MSI_DRIVER_FUNC(0x3000),MSI_API_FUNC
*/
#endif




#ifdef	TARGET_Record_2_Init2

   	#define UI_RECORD_VAR_DEF
   	#define AP_RECORD_INIT2_DEF
   	#define FILE_SYSTEM_FUNC_DEF
		#define FILE_SYSTEM_VAR_DEF
		#define FS_GET_83_NAME_DEF
		#define FS_FOPEN_APPOINTED_DEF
		#define FS_FOPEN_DEF
		#define FS_GET_FREE_SPACE_DEF
		#define FS_ENTER_DIR_DEF
		#define FS_GET_ITEM_NUM_DEF
		#define FS_ENTER_ROOT_DEF
		#define FS_GET_NEXT_FILE_INDIR_DEF

		#define MSI_SUPPORT_DEF

/*
?C_C51STARTUP(0x76),?PR?*?START_MAIN,LOAD_FUNC,SFC_DRIVER_SUB,SFC_DRIVER_READ,SFC_DRIVER_CLRBUF_0XFF,SFC_DRIVER_SUB1,?PR?*?AP_REC_INIT2(0x1C00),FS_BASIC_FUNC,?PR?*?API_FS,?PR?*?API_FS_SUB,?C?LIB_CODE,?PR?API_FS_SUB,?PR?API_FS,?PR?AP_REC_INIT2,MSI_DRIVER_FUNC(0x3000),MSI_API_FUNC
*/
#endif


#ifdef	TARGET_Record_3_Start_Sub

   	#define UI_RECORD_VAR_DEF
   	#define AP_RECORD_START_DEF
	#define ISR_RECORD_FUNC_DEF
   	#define FILE_SYSTEM_FUNC_DEF
		#define FILE_SYSTEM_VAR_DEF
			#define FS_FCREATE_DEF
			#define FS_FWRITE_DEF

			#define MSI_SUPPORT_DEF
/*
?C_C51STARTUP(0x76),?PR?*?START_MAIN,LOAD_FUNC,SFC_DRIVER_SUB,SFC_DRIVER_READ,SFC_DRIVER_CLRBUF_0XFF,SFC_DRIVER_SUB1,?PR?*?AP_REC_START(0x1C00),SFC_DRIVER_WRITE,API_SFC_WR_FUNC,API_SFC_INITPAR_FUNC,FS_BASIC_FUNC,?PR?*?API_FS,?C?LIB_CODE,?PR?API_FS,MSI_DRIVER_FUNC(0x3000),MSI_API_FUNC
*/
#endif

 
#ifdef	TARGET_Record_4_Stop_Sub

   	#define UI_RECORD_VAR_DEF
   	#define AP_RECORD_STOP_DEF
   	#define FILE_SYSTEM_FUNC_DEF
		#define FILE_SYSTEM_VAR_DEF
			#define FS_FWRITE_OVER_DEF
			#define FS_FWRITE_HEADER_DEF

			#define MSI_SUPPORT_DEF
/*
?C_C51STARTUP(0x76),?PR?*?START_MAIN,LOAD_FUNC,SFC_DRIVER_SUB,SFC_DRIVER_READ,SFC_DRIVER_CLRBUF_0XFF,SFC_DRIVER_SUB1,?PR?*?AP_REC_STOP(0x1C00),SFC_DRIVER_WRITE,API_SFC_WR_FUNC,API_SFC_INITPAR_FUNC,FS_BASIC_FUNC,?PR?*?API_FS,?C?LIB_CODE,?PR?AP_REC_STOP,MSI_DRIVER_FUNC(0x3000),MSI_API_FUNC
*/
#endif


   
#ifdef	TARGET_Record_5_Save_Para

   	#define UI_RECORD_VAR_DEF
   	#define AP_REC_SAVE_PARA_DEF
   	#define API_COMMON_FUNC_C_DEF
   	#define API_READ_SYS_PARA_TO_DBUF
   	#define FILE_SYSTEM_FUNC_DEF
		#define FILE_SYSTEM_VAR_DEF
		#define FS_INIT_OPEN_VAR_DE
		#define FS_WRITE_EF_INTERFACE	

		#define MSI_SUPPORT_DEF
/*
?C_C51STARTUP(0x76),?PR?*?START_MAIN,LOAD_FUNC,SFC_DRIVER_SUB,SFC_DRIVER_READ,SFC_DRIVER_CLRBUF_0XFF,SFC_DRIVER_SUB1,?PR?*?AP_REC_SAVE_PARA(0x1C00),SFC_DRIVER_WRITE,API_SFC_WR_FUNC,API_SFC_INITPAR_FUNC,FS_BASIC_FUNC,?C?LIB_CODE,?PR?API_READ_SYSPARA_TODBUF0?API_COMMON_FUNC,MSI_DRIVER_FUNC(0x3000),MSI_API_FUNC
*/
#endif



   
#ifdef	TARGET_Record_6_Get_Next_File

   	#define UI_RECORD_VAR_DEF
   	#define AP_RECORD_GET_NEW_FILE_DEF
   	#define FILE_SYSTEM_FUNC_DEF
		#define FILE_SYSTEM_VAR_DEF
		#define FS_SEC_TO_CLUSTER_DEF

		#define MSI_SUPPORT_DEF
/*
?C_C51STARTUP(0x76),?PR?*?START_MAIN,LOAD_FUNC,SFC_DRIVER_SUB,SFC_DRIVER_READ,SFC_DRIVER_CLRBUF_0XFF,SFC_DRIVER_SUB1,?PR?*?AP_REC_GET_NEW_FILE(0x1C00),?PR?*?API_FS,FS_BASIC_FUNC,?C?LIB_CODE,?PR?AP_REC_GET_NEW_FILE,MSI_DRIVER_FUNC(0x3000),MSI_API_FUNC
*/
#endif


#ifdef	TARGET_Record_7_Dynamic_Display
   	#define UI_RECORD_VAR_DEF

	#define	API_LCD_DRIVER_DEF
	#define	LCD_API_DEF
		#define API_LCD_DISPLAY_PICTURE
		#define API_LCD_DISPLAY_UNICODE
		#define API_LCD_DISPLAY_8x6ZIKU
		#define API_LCD_CLR_ASSIGNED_AREA
		#define API_DISPLAY_REVERSE_DEFINE
		#define API_LCD_REVERSE_DISPLAY
		
	#define	AP_REC_DYNAMIC_DISPLAY_DEF



/*
?C_C51STARTUP(0x76),?PR?*?START_MAIN,LOAD_FUNC,SFC_DRIVER_SUB,SFC_DRIVER_READ,SFC_DRIVER_CLRBUF_0XFF,SFC_DRIVER_SUB1,?PR?*?AP_REC_DYNAMIC_DISPLAY(0x1C00),LCD_INTERFACE_FUNC,LCD_FUNC,?CO?AP_REC_DYNAMIC_DISPLAY
*/
#endif

#ifdef TARGET_Record_8_SwitchCard
	#define UI_RECORD_VAR_DEF
	#define FB_SWITCH_CARD_DEF

	#define API_COMMON_FUNC_C_DEF
		#define API_DYNAMICLOAD_POWER_OFF

	#define FILE_SYSTEM_FUNC_DEF
		#define FILE_SYSTEM_VAR_DEF
		#define FS_POWER_ON_BOOT	

	#define MSI_SUPPORT_DEF
#endif
/*
?C_C51STARTUP(0x76),?PR?*?START_MAIN,LOAD_FUNC,SFC_DRIVER_SUB,SFC_DRIVER_READ,SFC_DRIVER_CLRBUF_0XFF,SFC_DRIVER_SUB1,?PR?*?FB_SWITCH_CARD(0x1C00),?PR?*?API_COMMON_FUNC,?PR?*?API_FS,FS_BASIC_FUNC,MSI_DRIVER_FUNC(0x3000),MSI_API_FUNC
*/

#ifdef TARGET_Voice_0_Main

   	#define UI_COMMON_FUNC_DEF
	   	#define UI_CHECK_REFRESH_MENU_FLAG
  	   	#define UI_PROCESS_EVT_BAT_SUB
		#define UI_POWER_ON_BKLIGHT
		#define UI_POWER_OFF_BKLIGHT
		#define UI_DIS_BATTERY_PIC
   	#define UI_VOICE_MAIN_DEF
	#define	UI_VOICE_PROCESS_KEY_DEF
	#define UI_VOICE_PROCESS_TIMER_DEF
	#define	UI_VOICE_PROCESS_DISPLAY_DEF
	#define UI_VOICE_VAR_DEF	 
	#define	AP_VOICE_PROCESS_DEF
	#define	AP_VOCIE_BASAL_DEF
	#define	AP_VOICE_COMMON_FUNC_DEF
	#define API_COMMON_FUNC_C_DEF
	   	//#define API_SYS_ENABLE_AUDIO_DEC_DEF
		#define API_SYS_ENABLE_VOICE_AUDIO_DEC_DEF
	   	#define API_DETECT_HEADPHONE_PLUG_DEF
		#define API_CHECK_BKLIGHT_OFF
	    #define API_CHECK_SLEEP_POWEROFF
		#define API_CHECK_IDLE_POWEROFF
		#define API_CHECK_BAT_DETECT
		#define API_KEY_MAPPING
		#define API_DYNAMICLOAD_USB
		#define	API_DYNAMICLOAD_POWER_OFF
		#define	API_DYNAMICLOAD_MAIN_MENU
	#define API_DYNAMICLOAD_TARGET_DEF
		#define API_DYNAMICLOAD_VOICE_TARGET
	#define API_COMMON_FUNC_ASM_DEF	
		#define API_SET_VOLUME_DEF
	#define API_COMMUNICANT_COMMAND_DEF
		#define API_CMD_START_DEC
		#define API_CMD_CONTROL_DEC
		#define API_CMD_RESET_DEC
		#define API_CMD_SET_FREQ_FADE
		#define API_CMD_FILL_OR_DIS_DBUF_OVER		
	#define	LCD_API_DEF
		#define API_LCD_DISPLAY_PICTURE
		#define API_LCD_DISPLAY_UNICODE
		#define API_LCD_DISPLAY_8x6ZIKU	 
		#define	API_LCD_CLR_ASSIGNED_AREA
		#define API_LCD_REVERSE_DISPLAY
		#define API_DISPLAY_REVERSE_DEFINE
  		#define	API_AUDIO_FILL_DBUF_EVENT
	#define ISR_VOICE_FUNC_DEF
	#define FILE_SYSTEM_FUNC_DEF
		#define FILE_SYSTEM_VAR_DEF
		#define FS_FREAD_DEF
	#define	API_LCD_DRIVER_DEF
	#define	FS_WRITE_EF_INTERFACE
	#define  MSI_READ_DEF	
 #define  MSI_SUPPORT_DEF

 #define AVOID_POP_NOISE
/*
?C_C51STARTUP(0x76),?PR?*?START_MAIN,LOAD_FUNC,SFC_DRIVER_SUB,SFC_DRIVER_READ,SFC_DRIVER_CLRBUF_0XFF,SFC_DRIVER_SUB1,?PR?*?UI_VOICE_MAIN(0x1190),DYNAMIC_FUNC_SEG,ISR_VOICE_FUNC,API_SFC_INITPAR_FUNC,?PR?*?UI_VOICE_KEY,?PR?*?UI_VOICE_PROCESS_TIMER,?PR?*?AP_VOICE_PROCESS_EVENT,?PR?*?UI_COMMON_FUNC,?PR?*?AP_VOICE_BASAL,?C?LIB_CODE,?CO?UI_COMMON_FUNC,?PR?*?UI_VOICE_DISPLAY,?CO?UI_VOICE_DISPLAY,COM_FUNC_SEG,API_COMMUNICANT_CMD,FS_BASIC_FUNC,?PR?*?API_FS,LCD_INTERFACE_FUNC,LCD_FUNC,?PR?API_CHECK_IDLE_POWEROFF?API_COMMON_FUNC,?PR?API_DYNAMICLOAD_POWEROFF?API_COMMON_FUNC,?PR?API_CHECK_SLEEP_POWEROFF?API_COMMON_FUNC,?PR?API_CHECK_BATTERY?API_COMMON_FUNC,?PR?API_DYNAMICLOAD_MAINMENU?API_COMMON_FUNC,?PR?API_DYNAMICLOAD_USB?API_COMMON_FUNC,?PR?API_CHECK_BKLIGHTOFF?API_COMMON_FUNC,?PR?API_KEY_MAPPING?API_COMMON_FUNC,?PR?AP_ENABLE_DAC?AP_VOICE_COMMON_FUNC,?PR?UI_VOICE_KEY,?PR?API_COMMON_FUNC,?PR?UI_VOICE_DISPLAY,?PR?API_MPEG_ENA_VOICEAUDIODEC?API_COMMON_FUNC,MSI_DRIVER_FUNC(0X3000),MSI_API_FUNC
*/
#endif


#ifdef	TARGET_Voice_1_Init1

   	#define UI_VOICE_VAR_DEF
   	#define AP_VOICE_INIT1_DEF
	#define API_COMMON_FUNC_C_DEF
		#define API_READ_SYS_PARA_TO_DBUF

 	#define FILE_SYSTEM_FUNC_DEF
		#define FILE_SYSTEM_VAR_DEF
		#define FS_GET_VOICE_DIR_DEF
	   	#define	FS_WRITE_EF_INTERFACE
	#define  MSI_READ_DEF	
	 #define  MSI_SUPPORT_DEF

   	#define API_COMMON_FUNC_ASM_DEF
		#define API_SET_VOLUME_DEF

#define AVOID_POP_NOISE

#define AP_VOICE_COMMON_FUNC_DEF
/*
?C_C51STARTUP(0x76),?PR?*?START_MAIN,LOAD_FUNC,SFC_DRIVER_SUB,SFC_DRIVER_READ,SFC_DRIVER_CLRBUF_0XFF,SFC_DRIVER_SUB1,?PR?*?AP_VOICE_INIT1(0x1C00),FS_BASIC_FUNC,?PR?*?API_FS,SFC_DRIVER_WRITE,?PR?API_READ_SYSPARA_TODBUF0?API_COMMON_FUNC,?C?LIB_CODE,API_SFC_INITPAR_FUNC,API_SFC_WR_FUNC,MSI_DRIVER_FUNC(0x3000),MSI_API_FUNC
*/
#endif

#ifdef	TARGET_Voice_2_Init2

   	#define UI_VOICE_VAR_DEF
   	#define AP_VOICE_INIT2_DEF
   	//#define API_COMMON_FUNC_ASM_DEF
	//	#define API_SET_VOLUME_DEF
	#define FILE_SYSTEM_FUNC_DEF
		#define FILE_SYSTEM_VAR_DEF
		#define FS_FOPEN_APPOINTED_DEF
		#define FS_FOPEN_DEF
		#define FS_CHECK_FILE_TYPE
		#define FS_ENTER_DIR_DEF
		#define FS_GET_ITEM_NUM_DEF
		#define FS_ENTER_ROOT_DEF
	//	#define FS_GET_VOICE_DIR_DEF//allen

	#define	FS_WRITE_EF_INTERFACE
	#define  MSI_READ_DEF	
	 #define  MSI_SUPPORT_DEF
/*
?C_C51STARTUP(0x76),?PR?*?START_MAIN,LOAD_FUNC,SFC_DRIVER_SUB,SFC_DRIVER_READ,SFC_DRIVER_CLRBUF_0XFF,SFC_DRIVER_SUB1,?PR?*?AP_VOICE_INIT2(0x1C00),FS_BASIC_FUNC,?PR?*?API_FS,?PR?*?API_FS_SUB,API_SFC_INITPAR_FUNC,COM_FUNC_SEG,?PR?AP_ENABLE_DAC?AP_VOICE_COMMON_FUNC,?C?LIB_CODE,?PR?API_FS_SUB,?PR?API_FS,SFC_DRIVER_WRITE,API_SFC_WR_FUNC,MSI_DRIVER_FUNC(0x3000),MSI_API_FUNC
*/
#endif

#ifdef	TARGET_Voice_3_Init_Play

   	#define UI_VOICE_VAR_DEF										 
   	#define AP_VOICE_INIT_PLAY_DEF
	#define API_COMMON_FUNC_ASM_DEF
		#define API_CONVERT_ISN_UNICODE
		#define API_MERGE_2BYTE_DEF
   	#define FILE_SYSTEM_FUNC_DEF
		#define FILE_SYSTEM_VAR_DEF
		#define FS_FREAD_DEF
		#define FS_GET_83_NAME_DEF

		#define MSI_SUPPORT_DEF
		
/*
?C_C51STARTUP(0x76),?PR?*?START_MAIN,LOAD_FUNC,SFC_DRIVER_SUB,SFC_DRIVER_READ,SFC_DRIVER_CLRBUF_0XFF,SFC_DRIVER_SUB1,?PR?*?AP_VOICE_INIT_PLAY(0x1C00),FS_BASIC_FUNC,?PR?*?API_FS,COM_FUNC_SEG,?C?LIB_CODE,?PR?AP_VOICE_INIT_PLAY,MSI_DRIVER_FUNC(0x3000),MSI_API_FUNC
*/
#endif



#ifdef	TARGET_Voice_4_Sel_File

   	#define UI_VOICE_VAR_DEF
   	#define AP_VOICE_SEL_FILE_DEF
   	#define FILE_SYSTEM_FUNC_DEF
		#define FILE_SYSTEM_VAR_DEF
		#define FS_INIT_OPEN_VAR_DEF
		#define FS_FOPEN_APPOINTED_DEF	
		#define FS_GET_NEXT_FILE_INDIR_DEF
		#define FS_FOPEN_DEF
	
	#define MSI_SUPPORT_DEF
/*
?C_C51STARTUP(0x76),?PR?*?START_MAIN,LOAD_FUNC,SFC_DRIVER_SUB,SFC_DRIVER_READ,SFC_DRIVER_CLRBUF_0XFF,SFC_DRIVER_SUB1,?PR?*?AP_VOICE_SEL_FILE(0x1C00),FS_BASIC_FUNC,?PR?*?API_FS,?PR?_GET_ITEM_INDEX?API_FS_SUB,?PR?DIR_FLAG_ADDR?API_FS_SUB,?PR?RAND?RAND,?C?LIB_CODE,?PR?AP_VOICE_SEL_FILE,?PR?API_FS_SUB,?PR?API_FS,MSI_DRIVER_FUNC(0x3000),MSI_API_FUNC
*/
#endif


#ifdef	TARGET_Voice_5_Fseek

   	#define UI_VOICE_VAR_DEF
   	#define AP_VOICE_FSEEK_DEF
   	#define FILE_SYSTEM_FUNC_DEF
		#define FILE_SYSTEM_VAR_DEF
		#define FS_FSEEK_DEF
		#define FS_FREAD_DEF
		#define MSI_SUPPORT_DEF
	
/*
?C_C51STARTUP(0x76),?PR?*?START_MAIN,LOAD_FUNC,SFC_DRIVER_SUB,SFC_DRIVER_READ,SFC_DRIVER_CLRBUF_0XFF,SFC_DRIVER_SUB1,?PR?*?AP_VOICE_FSEEK(0x1C00),FS_BASIC_FUNC,?PR?*?API_FS,?C?LIB_CODE,MSI_DRIVER_FUNC(0x3000),MSI_API_FUNC
*/
#endif



#ifdef TARGET_Voice_6_Del_File

   	#define UI_VOICE_VAR_DEF
   	#define FB_DELETE_FILE_DEF
	#define AP_VOICE_DELEATE_FILE_DEF
   	#define FILE_SYSTEM_FUNC_DEF
		#define FILE_SYSTEM_VAR_DEF
		#define FS_DELETE_DEF
		#define FS_FOPEN_APPOINTED_DEF	
		#define FS_INIT_OPEN_VAR_DEF
		#define MSI_SUPPORT_DEF	
/*
?C_C51STARTUP(0x76),?PR?*?START_MAIN,LOAD_FUNC,SFC_DRIVER_SUB,SFC_DRIVER_READ,SFC_DRIVER_CLRBUF_0XFF,SFC_DRIVER_SUB1,?PR?*?FB_DELETE_FILE(0x1C00),FS_BASIC_FUNC,?PR?*?API_FS,API_SFC_INITPAR_FUNC,?PR?_GET_ITEM_INDEX?API_FS_SUB,?PR?DIR_FLAG_ADDR?API_FS_SUB,API_SFC_WR_FUNC,SFC_DRIVER_WRITE,?C?LIB_CODE,?PR?FB_DELETE_FILE,?PR?API_FS_SUB,MSI_DRIVER_FUNC(0x3000),MSI_API_FUNC
*/
#endif


#ifdef	TARGET_Voice_7_Save_Para

   	#define UI_VOICE_VAR_DEF
   	#define AP_VOICE_SAVE_PARA_DEF 
   	#define FILE_SYSTEM_FUNC_DEF
		#define FILE_SYSTEM_VAR_DEF
		#define FS_INIT_OPEN_VAR_DE
		#define FS_WRITE_EF_INTERFACE	
		#define MSI_SUPPORT_DEF

/*
?C_C51STARTUP(0x76),?PR?*?START_MAIN,LOAD_FUNC,SFC_DRIVER_SUB,SFC_DRIVER_READ,SFC_DRIVER_CLRBUF_0XFF,SFC_DRIVER_SUB1,?PR?*?AP_VOICE_SAVE_PARA(0x1C00),?PR?AP_VOICE_SAVE_PARA,FS_BASIC_FUNC,API_SFC_INITPAR_FUNC,SFC_DRIVER_WRITE,API_SFC_WR_FUNC,?C?LIB_CODE,MSI_DRIVER_FUNC(0x3000),MSI_API_FUNC
*/
#endif
#ifdef TARGET_Voice_8_SwitchCard
	#define UI_VOICE_VAR_DEF
	#define FB_SWITCH_CARD_DEF

	#define API_COMMON_FUNC_C_DEF
		#define API_DYNAMICLOAD_POWER_OFF

	#define FILE_SYSTEM_FUNC_DEF
		#define FILE_SYSTEM_VAR_DEF
		#define FS_POWER_ON_BOOT
		#define FS_WRITE_EF_INTERFACE	

	#define MSI_SUPPORT_DEF
#endif
/*
?C_C51STARTUP(0x76),?PR?*?START_MAIN,LOAD_FUNC,SFC_DRIVER_SUB,SFC_DRIVER_READ,SFC_DRIVER_CLRBUF_0XFF,SFC_DRIVER_SUB1,?PR?*?FB_SWITCH_CARD(0x1C00),?PR?*?API_COMMON_FUNC,?PR?*?API_FS,FS_BASIC_FUNC,SFC_DRIVER_WRITE,API_SFC_INITPAR_FUNC,API_SFC_WR_FUNC,MSI_DRIVER_FUNC(0x3000),MSI_API_FUNC
*/
 
#ifdef TARGET_FM_0_Main
	#define UI_FM_MAIN_DEF
	#define UI_FM_KEY_PROCESS
	#define UI_FM_DISPLAY
	#define UI_FM_PROCESS_TIMER_DEF
	#define UI_FM_VAR_DEF
	#define UI_COMMON_FUNC_DEF
	   	#define UI_CHECK_REFRESH_MENU_FLAG
	   	#define UI_PROCESS_EVT_BAT_SUB
		#define UI_POWER_ON_BKLIGHT
		#define UI_POWER_OFF_BKLIGHT
		#define UI_DIS_BATTERY_PIC	
	#define	AP_FM_INIT_DEF
	#define AP_FM_PROCESS_DEF
	#define AP_FM_BASAL_DEF
	#define	AP_FM_DRV_FUNC_DEF
	#define AP_FM_INTERFACE

	#define API_COMMON_FUNC_C_DEF
	 	#define API_DETECT_HEADPHONE_PLUG_DEF
	 	#define API_CHECK_SLEEP_POWEROFF
		#define API_CHECK_BAT_DETECT
		#define API_CHECK_BKLIGHT_OFF
		#define API_KEY_MAPPING
		#define API_DYNAMICLOAD_USB
		#define API_DYNAMICLOAD_POWER_OFF
		#define API_DYNAMICLOAD_MAIN_MENU

	#define	API_COMMON_FUNC_ASM_DEF
	 	#define API_SET_FM_VOLUME_DEF
  	#define	API_DYNAMICLOAD_TARGET_DEF
	 	#define API_DYNAMICLOAD_FM_TARGET
		#define	API_DYNAMICLOAD_FM_CODE_MPM1_3K
		
	#define	LCD_API_DEF
		#define	API_LCD_DRIVER_DEF
		#define API_LCD_DISPLAY_PICTURE
		#define API_LCD_DISPLAY_8x6ZIKU
		#define API_LCD_CLR_ASSIGNED_AREA
		#define	API_LCD_REVERSE_DISPLAY
		#define	API_DISPLAY_REVERSE_DEFINE
	#define ISR_FM_FUNC_DEF
/*for test*/
/*	#define DRV_FM_COMMON
	#define DRV_FM_VAR_DEF
	#define DRV_FM_CL6017S
	#define AP_FM_RESTORE_PARA
		#define API_COMMON_FUNC_C_DEF
	   	#define API_READ_SYS_PARA_TO_DBUF
/*	   
?C_C51STARTUP(0x76),?PR?*?START_MAIN,LOAD_FUNC,SFC_DRIVER_SUB,SFC_DRIVER_READ,SFC_DRIVER_CLRBUF_0XFF,SFC_DRIVER_SUB1,?PR?*?UI_FM_MAIN(0x1190),DYNAMIC_FUNC_SEG,?PR?*?AP_FM_BASAL,ISR_FM_FUNC,?PR?*?UI_FM_KEY,?PR?*?UI_FM_DISPLAY,?PR?*?UI_FM_PROCESS_TIMER,?PR?*?UI_COMMON_FUNC,?CO?UI_COMMON_FUNC,?PR?*?AP_FM_PROCESS_EVENT,?PR?*?AP_FM_DRVFUNC,LCD_FUNC,LCD_INTERFACE_FUNC,COM_FUNC_SEG,?PR?*?API_COMMON_FUNC,?PR?*?AP_FM_INIT,AP_FM_INTERFACE_SEG,?PR?UI_FM_DISPLAY,?PR?UI_FM_KEY,?PR?API_COMMON_FUNC,?PR?AP_FM_DRVFUNC,?C?LIB_CODE

/*for test*/
/*
?C_C51STARTUP(0x76),?PR?*?START_MAIN,LOAD_FUNC,SFC_DRIVER_SUB,SFC_DRIVER_READ,SFC_DRIVER_CLRBUF_0XFF,SFC_DRIVER_SUB1,?PR?*?UI_FM_MAIN(0x1190),DYNAMIC_FUNC_SEG,?PR?*?AP_FM_BASAL,ISR_FM_FUNC,?PR?*?UI_FM_KEY,?PR?*?UI_FM_DISPLAY,?PR?*?UI_FM_PROCESS_TIMER,?PR?*?UI_COMMON_FUNC,?CO?UI_COMMON_FUNC,?PR?*?AP_FM_PROCESS_EVENT,?PR?*?AP_FM_DRVFUNC,LCD_FUNC,LCD_INTERFACE_FUNC,COM_FUNC_SEG,?PR?*?API_COMMON_FUNC,?PR?*?AP_FM_INIT

FM_DRV_VAR_SEG(0x6248),?XD?DRV_FM_AR1010,?XD?_API_RADIOSETSTEREO?DRV_FM_AR1010,?XD?FM_TUNING?DRV_FM_AR1010,?XD?_API_RADIOOPEN?DRV_FM_AR1010,?XD?_API_RADIOSETFREQ?DRV_FM_AR1010

FM_DRV_VAR_SEG(0x6248),?XD?FM_I2C_DECIDE_HLSI?DRV_FM_CL6017S,?XD?FM_I2C_TUNE_OVER?DRV_FM_CL6017S,?XD?FM_TUNING?DRV_FM_CL6017S,?XD?FM_I2C_CALCULATE_FREQ?DRV_FM_CL6017S,?XD?API_RADIOGETFREG?DRV_FM_CL6017S,?XD?FM_SEARCH_ONE_FREQ?DRV_FM_CL6017S
*/
#endif


 
#ifdef TARGET_FM_1_Restore_Para
	#define UI_FM_VAR_DEF
	#define AP_FM_RESTORE_PARA
	#define API_COMMON_FUNC_C_DEF
	   	#define API_READ_SYS_PARA_TO_DBUF
		#define FILE_SYSTEM_VAR_DEF

/*	   
?C_C51STARTUP(0x76),?PR?*?START_MAIN,LOAD_FUNC,SFC_DRIVER_SUB,SFC_DRIVER_READ,SFC_DRIVER_CLRBUF_0XFF,SFC_DRIVER_SUB1,?PR?*?AP_FM_RESTORE_PARA(0x1A00),?PR?*?API_COMMON_FUNC,?C?LIB_CODE,?PR?AP_FM_RESTORE_PARA
*/
#endif
 

 
#ifdef TARGET_FM_2_Save_Para
	#define UI_FM_VAR_DEF
	#define AP_FM_SAVE_PARA
	#define API_COMMON_FUNC_C_DEF
	   	#define API_READ_SYS_PARA_TO_DBUF
	#define FILE_SYSTEM_FUNC_DEF
		#define FILE_SYSTEM_VAR_DEF
		#define FS_WRITE_EF_INTERFACE

			#define	FS_NOT_SD_DEF

/*	   
?C_C51STARTUP(0x76),?PR?*?START_MAIN,LOAD_FUNC,SFC_DRIVER_SUB,SFC_DRIVER_READ,SFC_DRIVER_CLRBUF_0XFF,SFC_DRIVER_SUB1,?PR?*?AP_FM_SAVE_PARA(0x1A00),?PR?*?API_COMMON_FUNC,FS_BASIC_FUNC,SFC_DRIVER_WRITE,API_SFC_INITPAR_FUNC,API_SFC_WR_FUNC,?C?LIB_CODE,?PR?AP_FM_SAVE_PARA
*/
#endif


#ifdef TARGET_FM_3_DrvTea5767
	#define DRV_FM_INTERFACE
	#define DRV_FM_COMMON
	#define DRV_FM_VAR_DEF
	#define DRV_FM_TEA5767
   	#define	FS_NOT_SD_DEF

/*
?C_C51STARTUP(0x76),?PR?*?START_MAIN,LOAD_FUNC,SFC_DRIVER_SUB,SFC_DRIVER_READ,SFC_DRIVER_CLRBUF_0XFF,SFC_DRIVER_SUB1,?PR?*?DRV_FM_TEA5767(0x25251B),DRV_FM_COMMON_SEG,?C?LIB_CODE,?PR?DRV_FM_TEA5767

?XD?*?DRV_FM_TEA5767(0x7350)
*/
#endif

#ifdef TARGET_FM_5_DrvAR1010
	#define DRV_FM_INTERFACE
	#define DRV_FM_COMMON
	#define DRV_FM_VAR_DEF
	#define DRV_FM_AR1010
		#define	FS_NOT_SD_DEF

/*
?C_C51STARTUP(0x76),?PR?*?START_MAIN,LOAD_FUNC,SFC_DRIVER_SUB,SFC_DRIVER_READ,SFC_DRIVER_CLRBUF_0XFF,SFC_DRIVER_SUB1,?PR?*?DRV_FM_AR1010(0x251B),DRV_FM_COMMON_SEG,?C?LIB_CODE,?CO?DRV_FM_AR1010,?PR?DRV_FM_AR1010

?XD?DRV_FM_AR1010(0x7350),?XD?*?DRV_FM_AR1010
*/
#endif

#ifdef TARGET_FM_6_DrvCL6017S
	#define DRV_FM_INTERFACE
	#define DRV_FM_COMMON
	#define DRV_FM_VAR_DEF
	#define DRV_FM_CL6017S
		#define	FS_NOT_SD_DEF

/*
?C_C51STARTUP(0x76),?PR?*?START_MAIN,LOAD_FUNC,SFC_DRIVER_SUB,SFC_DRIVER_READ,SFC_DRIVER_CLRBUF_0XFF,SFC_DRIVER_SUB1,?PR?*?DRV_FM_CL6017S(0x251B),DRV_FM_COMMON_SEG,?CO?DRV_FM_CL6017S,?C?LIB_CODE,?PR?DRV_FM_CL6017S

?XD?*?DRV_FM_CL6017S(0x7350)
*/
#endif


#ifdef TARGET_FM_7_DrvSI4702
	#define DRV_FM_INTERFACE
	#define DRV_FM_COMMON
	#define DRV_FM_VAR_DEF
	#define DRV_FM_SI4702
   	#define	FS_NOT_SD_DEF

/*
?C_C51STARTUP(0x76),?PR?*?START_MAIN,LOAD_FUNC,SFC_DRIVER_SUB,SFC_DRIVER_READ,SFC_DRIVER_CLRBUF_0XFF,SFC_DRIVER_SUB1,?PR?*?DRV_FM_SI4702(0x251B),DRV_FM_COMMON_SEG,?C?LIB_CODE,?PR?DRV_FM_SI4702,?CO?DRV_FM_SI4702

?XD?*?DRV_FM_SI4702(0x7350)
*/
#endif


#ifdef TARGET_FM_8_DrvRda5807SP
	#define DRV_FM_INTERFACE
	#define DRV_FM_COMMON
	#define DRV_FM_VAR_DEF
	#define DRV_FM_RDA5807SP
		#define	FS_NOT_SD_DEF

/*
?C_C51STARTUP(0x76),?PR?*?START_MAIN,LOAD_FUNC,SFC_DRIVER_SUB,SFC_DRIVER_READ,SFC_DRIVER_CLRBUF_0XFF,SFC_DRIVER_SUB1,?PR?*?DRV_FM_Rda5807SP(0x251B),DRV_FM_COMMON_SEG,?C?LIB_CODE,?PR?DRV_FM_RDA5807SP

?XD?*?DRV_FM_RDA5807SP(0x7350)
*/
#endif


#ifdef TARGET_FM_9_DrvBK1080
	#define DRV_FM_INTERFACE
	#define DRV_FM_COMMON
	#define DRV_FM_VAR_DEF
	#define DRV_FM_BK1080
		#define	FS_NOT_SD_DEF

/*
?C_C51STARTUP(0x76),?PR?*?START_MAIN,LOAD_FUNC,SFC_DRIVER_SUB,SFC_DRIVER_READ,SFC_DRIVER_CLRBUF_0XFF,SFC_DRIVER_SUB1,?PR?*?DRV_FM_BK1080(0x251B),DRV_FM_COMMON_SEG,?C?LIB_CODE,?PR?DRV_FM_BK1080,?CO?DRV_FM_BK1080

?XD?*?DRV_FM_BK1080(0x7350)
*/
#endif





#ifdef TARGET_Ebook_0_Main

	#define UI_EBOOK_MAIN_DEF
	#define UI_EBOOK_PROCESS_KEY_DEF
	#define UI_EBOOK_PROCESS_DISPLAY_DEF
	#define UI_EBOOK_TIMER_DEF
	#define UI_EBOOK_VAR_DEF
	#define UI_COMMON_FUNC_DEF
		#define UI_CHECK_REFRESH_MENU_FLAG	 //allen
		#define UI_DIS_BATTERY_PIC
   		#define UI_PROCESS_EVT_BAT_SUB
		#define UI_POWER_ON_BKLIGHT
		#define UI_POWER_OFF_BKLIGHT
	#define AP_EBOOK_EVENT_PROCESS
	#define	AP_EBOOK_COMMON_FUNC_DEF
	#define API_COMMON_FUNC_C_DEF
		#define API_CHECK_BAT_DETECT
	  	#define API_KEY_MAPPING
		#define API_CHECK_SLEEP_POWEROFF
		#define API_CHECK_IDLE_POWEROFF
		#define API_CHECK_BAT_DETECT
		#define API_CHECK_BKLIGHT_OFF
		#define API_DYNAMICLOAD_USB
		#define API_DYNAMICLOAD_POWER_OFF
		#define API_DYNAMICLOAD_MAIN_MENU
	#define API_DYNAMICLOAD_TARGET_DEF
		#define API_DYNAMICLOAD_EBOOK_TARGET

	#define API_COMMON_FUNC_ASM_DEF
		#define API_CONVERT_ISN_UNICODE
		#define API_MERGE_2BYTE_DEF
	#define	LCD_API_DEF
		#define API_LCD_DISPLAY_PICTURE
		#define API_LCD_DISPLAY_UNICODE
		#define API_LCD_DISPLAY_8x6ZIKU
		#define API_DISPLAY_REVERSE_DEFINE
		#define	API_LCD_REVERSE_DISPLAY

	#define FILE_SYSTEM_FUNC_DEF
		#define FILE_SYSTEM_VAR_DEF
		#define FS_FOPEN_APPOINTED_DEF
		#define FS_FREAD_DEF
		#define FS_FSEEK_DEF																																																																																																											  
		#define FS_INIT_OPEN_VAR_DEF
		#define ISR_EBOOK_FUNC_DEF
	#define	API_LCD_DRIVER_DEF


	#define MSI_SUPPORT_DEF
/*
?C_C51STARTUP(0x76),?PR?*?START_MAIN,LOAD_FUNC,SFC_DRIVER_SUB,SFC_DRIVER_READ,SFC_DRIVER_CLRBUF_0XFF,SFC_DRIVER_SUB1,?PR?*?UI_EBOOK_MAIN(0x1190),DYNAMIC_FUNC_SEG,ISR_EBOOK_FUNC,?PR?*?UI_EBOOK_KEY,?PR?*?UI_EBOOK_DISPLAY,?PR?*?AP_EBOOK_EVENT,?PR?*?UI_EBOOK_TIMER,?PR?*?UI_COMMON_FUNC,?PR?*?AP_EBOOK_COMMON_FUNC,?CO?UI_COMMON_FUNC,?PR?*?API_FS,?PR?*?API_FS_SUB,FS_BASIC_FUNC,LCD_INTERFACE_FUNC,LCD_FUNC,?C?LIB_CODE,MSI_DRIVER_FUNC(0x3000),MSI_API_FUNC,?PR?API_FS,COM_FUNC_SEG,?PR?UI_EBOOK_TIMER,?PR?UI_EBOOK_DISPLAY,?CO?UI_EBOOK_DISPLAY,?PR?UI_EBOOK_KEY,?PR?AP_EBOOK_EVENT,?PR?AP_EBOOK_COMMON_FUNC,?PR?*?API_COMMON_FUNC,?PR?API_COMMON_FUNC,?PR?API_FS_SUB
*/
#endif




#ifdef TARGET_Ebook_1_Init

	#define UI_EBOOK_VAR_DEF
	#define AP_EBOOK_INIT_DEF
	#define FILE_SYSTEM_FUNC_DEF
		#define FILE_SYSTEM_VAR_DEF
		#define FS_EXIT_DIR_DEF
		#define FS_FOPEN_DEF
		#define FS_INIT_OPEN_VAR_DEF
		#define FS_GET_FILEPATH_DEF
		#define FS_CHECK_FILE_TYPE
		#define FS_ENTER_DIR_DEF
		#define FS_GET_ITEM_NUM_DEF
		#define FS_ENTER_ROOT_DEF
		#define FS_ENTER_APPOINTED_DIR_DEF
	#define MSI_SUPPORT_DEF

/*
?C_C51STARTUP(0x76),?PR?*?START_MAIN,LOAD_FUNC,SFC_DRIVER_SUB,SFC_DRIVER_READ,SFC_DRIVER_CLRBUF_0XFF,SFC_DRIVER_SUB1,?PR?*?AP_EBOOK_INIT(0x1C00),?PR?*?API_FS,?PR?*?API_FS_SUB,FS_BASIC_FUNC,?C?LIB_CODE,?PR?AP_EBOOK_INIT,?PR?API_FS_SUB,MSI_DRIVER_FUNC(0x3000),MSI_API_FUNC
*/
#endif

#ifdef TARGET_Ebook_2_Init_Play

	#define UI_EBOOK_VAR_DEF
	#define AP_EBOOK_INIT_PLAY_DEF
	#define API_COMMON_FUNC_ASM_DEF
		#define API_CONVERT_ISN_UNICODE
		#define API_MERGE_2BYTE_DEF
	#define FILE_SYSTEM_FUNC_DEF
		#define FILE_SYSTEM_VAR_DEF
		#define FS_GET_83_NAME_DEF
		#define FS_GET_LONG_NAME_DEF
		#define SECTRO_TO_CLUSTER
	   	#define MSI_SUPPORT_DEF


/*
?C_C51STARTUP(0x76),?PR?*?START_MAIN,LOAD_FUNC,SFC_DRIVER_SUB,SFC_DRIVER_READ,SFC_DRIVER_CLRBUF_0XFF,SFC_DRIVER_SUB1,?PR?*?AP_EBOOK_INIT_PLAY(0x1C00),?PR?*?API_FS,FS_BASIC_FUNC,?C?LIB_CODE,COM_FUNC_SEG,?PR?AP_EBOOK_INIT_PLAY,MSI_DRIVER_FUNC(0x3000),MSI_API_FUNC
*/
#endif



#ifdef TARGET_Ebook_3_Get_Page_Num

	#define UI_EBOOK_VAR_DEF
	#define AP_EBOOK_GET_PAGE_NUMBER_DEF
	#define	AP_EBOOK_COMMON_FUNC_DEF
	#define API_COMMON_FUNC_ASM_DEF
		#define API_CONVERT_ISN_UNICODE
		#define API_MERGE_2BYTE_DEF
	#define FILE_SYSTEM_FUNC_DEF
		#define FILE_SYSTEM_VAR_DEF
		#define FS_FREAD_DEF
	#define FS_WRITE_EF_INTERFACE
	  	#define MSI_SUPPORT_DEF

/*
?C_C51STARTUP(0x76),?PR?*?START_MAIN,LOAD_FUNC,SFC_DRIVER_SUB,SFC_DRIVER_READ,SFC_DRIVER_CLRBUF_0XFF,SFC_DRIVER_SUB1,?PR?*?AP_EBOOK_GET_PAGENUM(0x1C00),?PR?*?API_FS,FS_BASIC_FUNC,?PR?*?AP_EBOOK_COMMON_FUNC,?C?LIB_CODE,COM_FUNC_SEG,SFC_DRIVER_WRITE,API_SFC_INITPAR_FUNC,API_SFC_WR_FUNC,?PR?AP_EBOOK_COMMON_FUNC,?PR?AP_EBOOK_GET_PAGENUM,MSI_DRIVER_FUNC(0x3000),MSI_API_FUNC
*/
#endif


#ifdef TARGET_Ebook_4_Save_Para

	#define UI_EBOOK_VAR_DEF
	#define AP_EBOOK_SAVE_PARA_DEF
	#define FILE_SYSTEM_FUNC_DEF
		#define FILE_SYSTEM_VAR_DEF
		#define FS_WRITE_EF_INTERFACE	
		 	#define MSI_SUPPORT_DEF
/*		
?C_C51STARTUP(0x76),?PR?*?START_MAIN,LOAD_FUNC,SFC_DRIVER_SUB,SFC_DRIVER_READ,SFC_DRIVER_CLRBUF_0XFF,SFC_DRIVER_SUB1,?PR?*?AP_EBOOK_SAVE_PARA(0x1C00),FS_BASIC_FUNC,SFC_DRIVER_WRITE,API_SFC_INITPAR_FUNC,API_SFC_WR_FUNC,MSI_DRIVER_FUNC(0x3000),MSI_API_FUNC
*/
#endif


#ifdef TARGET_Ebook_5_Del_File

	#define UI_EBOOK_VAR_DEF
	#define AP_EBOOK_DEL_FILE
	#define FB_DELETE_FILE_DEF
	#define FILE_SYSTEM_FUNC_DEF
		#define FILE_SYSTEM_VAR_DEF
		#define FS_DELETE_DEF
		#define FS_FOPEN_APPOINTED_DEF
				#define FS_INIT_OPEN_VAR_DEF
		 	#define MSI_SUPPORT_DEF

/*		
?C_C51STARTUP(0x76),?PR?*?START_MAIN,LOAD_FUNC,SFC_DRIVER_SUB,SFC_DRIVER_READ,SFC_DRIVER_CLRBUF_0XFF,SFC_DRIVER_SUB1,?PR?*?FB_DELETE_FILE(0x1C00),?PR?*?API_FS,FS_BASIC_FUNC,SFC_DRIVER_WRITE,API_SFC_WR_FUNC,API_SFC_INITPAR_FUNC,?C?LIB_CODE,?PR?FB_DELETE_FILE,?PR?DIR_FLAG_ADDR?API_FS_SUB,?PR?API_FS_SUB,?PR?_GET_ITEM_INDEX?API_FS_SUB,MSI_DRIVER_FUNC(0x3000),MSI_API_FUNC
*/
#endif
 


#ifdef TARGET_Ebook_6_Get_Item_Num

	#define UI_EBOOK_VAR_DEF
	#define FB_GET_ITEM_NUM_DEF
	#define AP_EBOOK_GET_ITEM_NUM
	#define FILE_SYSTEM_FUNC_DEF
		#define FILE_SYSTEM_VAR_DEF
		#define FS_EXIT_DIR_DEF
		#define FS_ENTER_DIR_DEF
		#define FS_GET_ITEM_NUM_DEF
		 	#define MSI_SUPPORT_DEF

/*		
?C_C51STARTUP(0x76),?PR?*?START_MAIN,LOAD_FUNC,SFC_DRIVER_SUB,SFC_DRIVER_READ,SFC_DRIVER_CLRBUF_0XFF,SFC_DRIVER_SUB1,?PR?*?FB_GET_ITEM_NUM(0x1C00),?PR?*?API_FS,FS_BASIC_FUNC,?PR?_GET_ITEM_INDEX?API_FS_SUB,?PR?DIR_FLAG_ADDR?API_FS_SUB,?C?LIB_CODE,?PR?API_FS_SUB,MSI_DRIVER_FUNC(0x3000),MSI_API_FUNC
*/
#endif



#ifdef TARGET_Ebook_7_Get_Item_Name

	#define UI_EBOOK_VAR_DEF
	#define FB_GET_ITEM_NAME_DEF
	#define AP_EBOOK_GET_ITEM_NAME
	#define API_COMMON_FUNC_ASM_DEF
		#define API_CONVERT_ISN_UNICODE
		#define API_MERGE_2BYTE_DEF

	#define FILE_SYSTEM_FUNC_DEF
		#define FILE_SYSTEM_VAR_DEF
		#define FS_GET_83_NAME_DEF
		#define FS_GET_LONG_NAME_DEF
		#define FS_OPEN_DIR_DEF
		#define FS_FOPEN_APPOINTED_DEF
		#define FS_FOPEN_DEF
		#define FS_GET_NEXT_FILE_INDIR_DEF
		#define FS_EXIT_DIR_DEF
		#define FS_INIT_OPEN_VAR_DEF
		#define FS_ENTER_DIR_DEF
		 #define MSI_SUPPORT_DEF
/*		 	
?C_C51STARTUP(0x76),?PR?*?START_MAIN,LOAD_FUNC,SFC_DRIVER_SUB,SFC_DRIVER_READ,SFC_DRIVER_CLRBUF_0XFF,SFC_DRIVER_SUB1,?PR?*?FB_GET_ITEM_NAME(0x1C00),?PR?*?API_FS,FS_BASIC_FUNC,COM_FUNC_SEG,?PR?_GET_ITEM_INDEX?API_FS_SUB,?PR?DIR_FLAG_ADDR?API_FS_SUB,?C?LIB_CODE,?PR?API_FS_SUB,?PR?API_FS,MSI_DRIVER_FUNC(0x3000),MSI_API_FUNC
*/
#endif




#ifdef TARGET_Ebook_8_SwitchCard
	#define UI_EBOOK_VAR_DEF
	#define FB_SWITCH_CARD_DEF

	#define API_COMMON_FUNC_C_DEF
		#define API_DYNAMICLOAD_POWER_OFF

	#define FILE_SYSTEM_FUNC_DEF
		#define FILE_SYSTEM_VAR_DEF
		#define FS_POWER_ON_BOOT
	//	#define FS_ENTER_DIR_DEF
	//	#define FS_EXIT_DIR_DEF
	//	#define FS_GET_ITEM_NUM_DEF	
	//	#define FS_GET_FILEPATH_DEF
		#define FS_ENTER_ROOT_DEF
	//	#define FS_ENTER_APPOINTED_DIR_DEF
	//	#define FS_FOPEN_DEF
	//	#define FS_CHECK_FILE_TYPE
		#define FS_GET_ITEM_NUM_DEF		
		#define FS_INIT_OPEN_VAR_DEF	
	#define MSI_SUPPORT_DEF
#endif
/*
?C_C51STARTUP(0x76),?PR?*?START_MAIN,LOAD_FUNC,SFC_DRIVER_SUB,SFC_DRIVER_READ,SFC_DRIVER_CLRBUF_0XFF,SFC_DRIVER_SUB1,?PR?*?FB_SWITCH_CARD(0x1C00),?PR?*?API_FS,?PR?API_DYNAMICLOAD_POWEROFF?API_COMMON_FUNC,?C?LIB_CODE,?PR?API_FS_SUB,FS_BASIC_FUNC,?PR?DIR_FLAG_ADDR?API_FS_SUB,MSI_DRIVER_FUNC(0x3000),MSI_API_FUNC
*/



#ifdef	TARGET_Tel_0_Main

   	#define UI_TELBOOK_MAIN_DEF
   	#define UI_TELBOOK_KEY_DEF
	#define UI_TELBOOK_DISPLAY_DEF	 
   	#define UI_TELBOOK_PROCESS_TIMER_DEF
	#define UI_TELBOOK_VAR_DEF
	#define UI_COMMON_FUNC_DEF
		#define UI_PROCESS_EVT_BAT_SUB	
		#define UI_POWER_ON_BKLIGHT
		#define UI_POWER_OFF_BKLIGHT
		#define UI_DIS_HOLD_PIC	
		#define UI_CHECK_REFRESH_MENU_FLAG	
	#define AP_TELBOOK_INIT_DEF
	#define AP_TELBOOK_ENHANCE_DEF
	#define AP_TELBOOK_PROCESS_DEF
	#define API_COMMON_FUNC_C_DEF
		#define API_CHECK_BKLIGHT_OFF	
		#define API_CHECK_BAT_DETECT
		#define API_CHECK_IDLE_POWEROFF	
 		#define API_CHECK_SLEEP_POWEROFF	
		#define API_KEY_MAPPING
		#define API_READ_SYS_PARA_TO_DBUF	
		#define API_DYNAMICLOAD_USB	
		#define API_DYNAMICLOAD_MAIN_MENU
		#define API_DYNAMICLOAD_POWER_OFF
	#define	API_COMMON_FUNC_ASM_DEF
		#define API_CONVERT_ISN_UNICODE	
		#define API_MERGE_2BYTE_DEF	
	#define API_DYNAMICLOAD_TARGET_DEF	
		#define API_DYNAMICLOAD_TEL_TARGET	
	#define FILE_SYSTEM_FUNC_DEF
		#define FILE_SYSTEM_VAR_DEF
		#define FS_WRITE_EF_INTERFACE	
		#define FS_GET_ITEM_NUM_DEF
		#define FS_ENTER_ROOT_DEF
		#define FS_INIT_OPEN_VAR_DEF
		#define FS_GET_FREE_SPACE_DEF
		//#define FS_POWER_ON_BOOT
		
	        #define	LCD_API_DEF
		#define API_LCD_DISPLAY_PICTURE
		#define API_LCD_DISPLAY_UNICODE
		#define API_LCD_DISPLAY_8x6ZIKU
		#define API_DISPLAY_REVERSE_DEFINE
		#define	API_LCD_REVERSE_DISPLAY

	#define	ISR_TELBOOK_FUNC_DEF
	#define	API_LCD_DRIVER_DEF
	#define	FS_NOT_SD_DEF
/*
?C_C51STARTUP(0x76),?PR?*?START_MAIN,LOAD_FUNC,SFC_DRIVER_SUB,SFC_DRIVER_READ,SFC_DRIVER_CLRBUF_0XFF,SFC_DRIVER_SUB1,?PR?*?UI_TELBOOK_MAIN(0x1190),DYNAMIC_FUNC_SEG,ISR_TELBOOK_FUNC,?PR?*?UI_TELBOOK_KEY,?PR?*?UI_TELBOOK_DISPLAY,?PR?*?UI_TELBOOK_PROCESS_TIMER,?PR?*?UI_COMMON_FUNC,?CO?UI_COMMON_FUNC,?PR?*?AP_TELBOOK_ENHANCE,?PR?*?AP_TELBOOK_PROCESS_EVENT,?PR?*?API_COMMON_FUNC,COM_FUNC_SEG,FS_BASIC_FUNC,LCD_INTERFACE_FUNC,LCD_FUNC,API_SFC_WR_FUNC,API_SFC_INITPAR_FUNC,?C?LIB_CODE,?CO?UI_TELBOOK_DISPLAY,?CO?AP_TELBOOK_INIT,?PR?AP_TELBOOK_ENHANCE,?PR?UI_TELBOOK_DISPLAY,?PR?API_COMMON_FUNC,?PR?AP_TELBOOK_INIT,?PR?AP_INIT_TELFILE?AP_TELBOOK_INIT,?PR?*?API_FS,?PR?API_FS_SUB,?PR?DIR_FLAG_ADDR?API_FS_SUB
*/
#endif



#ifdef	TARGET_Tel_1_Del_Old_File

   	#define UI_TELBOOK_VAR_DEF
   	#define AP_TELBOOK_DEL_OLD_FILE_DEF
		#define FILE_SYSTEM_FUNC_DEF
		#define FILE_SYSTEM_VAR_DEF	  
		#define FS_DELETE_DEF
		#define FS_GET_83_NAME_DEF
		//#define FS_GET_ITEM_NUM_DEF
		//#define FS_ENTER_ROOT_DEF
		//#define FS_INIT_OPEN_VAR_DEF
		#define FS_CHECK_FILE_TYPE
		#define FS_FOPEN_DEF
			#define	FS_NOT_SD_DEF
/*
?C_C51STARTUP(0x76),?PR?*?START_MAIN,LOAD_FUNC,SFC_DRIVER_SUB,SFC_DRIVER_READ,SFC_DRIVER_CLRBUF_0XFF,SFC_DRIVER_SUB1,?PR?*?AP_TELBOOK_DEL_OLD_FILE(0x1C00),?PR?*?API_FS,?PR?*?API_FS_SUB,FS_BASIC_FUNC,SFC_DRIVER_WRITE,API_SFC_WR_FUNC,API_SFC_INITPAR_FUNC,?C?LIB_CODE,?PR?API_FS_SUB
*/
#endif



#ifdef	TARGET_Tel_2_Import

   	#define UI_TELBOOK_VAR_DEF
   	#define AP_TELBOOK_IMPORTE_DEF
	#define FILE_SYSTEM_FUNC_DEF
		#define FILE_SYSTEM_VAR_DEF	  
		#define FS_FREAD_DEF
		#define FS_DELETE_DEF
			#define	FS_NOT_SD_DEF
			#define FS_WRITE_EF_INTERFACE
/*
?C_C51STARTUP(0x76),?PR?*?START_MAIN,LOAD_FUNC,SFC_DRIVER_SUB,SFC_DRIVER_READ,SFC_DRIVER_CLRBUF_0XFF,SFC_DRIVER_SUB1,?PR?*?AP_TELBOOK_IMPORT(0x1C00),SFC_DRIVER_WRITE,?PR?*?API_FS,FS_BASIC_FUNC,?C?LIB_CODE,API_SFC_WR_FUNC,API_SFC_INITPAR_FUNC
*/
#endif

 


#ifdef	TARGET_Tel_3_Export

   	#define UI_TELBOOK_VAR_DEF
   	#define AP_TELBOOK_EXPORT_DEF
	#define FILE_SYSTEM_FUNC_DEF
		#define FILE_SYSTEM_VAR_DEF	  
		#define FS_FWRITE_DEF		  
		#define FS_FCREATE_DEF
		#define FS_FWRITE_OVER_DEF
		#define FS_FWRITE_HEADER_DEF
		//#define FS_GET_FREE_SPACE_DEF
			#define	FS_NOT_SD_DEF
/*
?C_C51STARTUP(0x76),?PR?*?START_MAIN,LOAD_FUNC,SFC_DRIVER_SUB,SFC_DRIVER_READ,SFC_DRIVER_CLRBUF_0XFF,SFC_DRIVER_SUB1,?PR?*?AP_TELBOOK_EXPORT(0x1C00),SFC_DRIVER_WRITE,?PR?*?API_FS,FS_BASIC_FUNC,?C?LIB_CODE,API_SFC_INITPAR_FUNC,API_SFC_WR_FUNC,?PR?API_FS
*/
#endif


#ifdef	TARGET_Tel_4_Check_Tel_File

   	#define UI_TELBOOK_VAR_DEF
   	#define AP_CHECK_TEL_FILE_DEF
	#define FILE_SYSTEM_FUNC_DEF
		#define FILE_SYSTEM_VAR_DEF	  
		#define FS_ENTER_ROOT_DEF		 
		#define FS_GET_ITEM_NUM_DEF
		#define FS_CHECK_FILE_TYPE
		#define FS_FSEEK_DEF
		#define FS_FOPEN_DEF
		#define FS_GET_83_NAME_DEF		
		#define FS_FREAD_DEF
		#define FS_INIT_OPEN_VAR_DEF
			#define	FS_NOT_SD_DEF


/*
?C_C51STARTUP(0x76),?PR?*?START_MAIN,LOAD_FUNC,SFC_DRIVER_SUB,SFC_DRIVER_READ,SFC_DRIVER_CLRBUF_0XFF,SFC_DRIVER_SUB1,?PR?*?AP_TELBOOK_CHECK_FILE_EXIST(0x1C00),?PR?*?API_FS,?PR?*?API_FS_SUB,FS_BASIC_FUNC,?C?LIB_CODE,?PR?AP_TELBOOK_CHECK_FILE_EXIST,?PR?API_FS,?PR?API_FS_SUB
*/
#endif




#ifdef	FS_POWER_ON_BOOT
	#define	FS_READ_SECTOR
	#define R_SH16_DEF
	#define ADD_32_DEF
	#define SUB_32_DEF
	#define CLST_EXP_DEF
	#define	R_SH32_DEF
	#define	L_SH32_DEF
#endif


#ifdef	FS_GET_ITEM_NUM_DEF
	#define	BEG_CLST_ADDR_DEF
	#define	GET_ITEM_NUM
	#define	FS_READ_SECTOR
	#define CLST_1_SECT_RD_DEF
	#define PARSE_ITEM_DEF
	#define FILE_CHK_MODULE
	#define	NXT_SECTOR_DEF
	#define	INC_ADDR_DEF
	#define	CLST_1_SECT_CAL_DEF
	#define	PARSE_CLST_2FAT_DEF
	#define	ADD_32_DEF
	#define	R_SH32_DEF
#endif


#ifdef	FS_FSEEK_DEF
	#define	NXT_CLST_DEF
	#define	CLST_EXP_DEF
	#define	R_SH32_DEF
	#define	FS_READ_SECTOR
	#define	PARSE_CLST_2FAT_DEF
#endif


#ifdef	FS_FREAD_DEF
	#define	CLST_1_SECT_CAL_DEF
	#define	FS_READ_SECTOR
	#define	ADD_32_DEF
	#define	NXT_SECTOR_DEF
	#define	INC_ADDR_DEF
	#define	PARSE_CLST_2FAT_DEF
	#define	R_SH32_DEF
	#define	CAL_ADDRESS
	#define	FS_READ_SECTOR_TO_POINT
#endif


#ifdef FS_GET_PREVIOUS_SECTOR_DEF
	#define FS_FREAD_PREVIOUS_SECTOR_DEF
	#define SECTRO_TO_CLUSTER
#endif


#ifdef	FS_FREAD_PREVIOUS_SECTOR_DEF
	#define	PREV_SECTOR_DEF
	#define	FS_READ_SECTOR_TO_POINT
	#define	DEC_ADDR_DEF
	#define	NXT_CLST_DEF
	#define	CLST_1_SECT_CAL_DEF
	#define	CAL_ADDRESS
	#define	SUB_32_DEF
	#define	CLST_EXP_DEF
	#define	R_SH32_DEF
	#define L_SH32_DEF
	#define R_SH16_DEF
	#define L_SH16_DEF
	#define	ADD_32_DEF
	#define	FS_READ_SECTOR
	#define	PARSE_CLST_2FAT_DEF
#endif


#ifdef	FS_FWRITE_DEF
	#define	SRH_FREE_IN_FAT_DEF
	#define	COPY_512B_DEF
	#define	SRH_BLANK_DEF
	#define	WR_SECTOR_SRC_FATBUF
	#define	FAT_CAL_CLST_DEF
	#define	CHK_CAPACITY_DEF
	#define SUB_32_DEF
	#define	CLST_1_SECT_CAL_DEF
	#define	FS_READ_SECTOR
	#define	FS_WRITE_SECTOR
	#define	FS_WRITE_INTERFACE
	#define	ADD_32_DEF
	#define	INC_ADDR_DEF
	#define	FAT1_BOUNDARY_CHK_DEF
	#define	L_SH16_DEF
	#define	R_SH16_DEF
	#define	L_SH32_DEF
	#define	ADD_32_DEF
	#define	CLST_EXP_DEF
	#define	FS_WRITE_SECTOR_TO_POINT
	
	#define	API_SFC_INTERFACE_WR
#endif


#ifdef	FS_FWRITE_OVER_DEF
	#define	WR_SECTOR_SRC_FATBUF
	#define	FS_READ_SECTOR
	#define	FS_WRITE_SECTOR
	#define	CLST_1_SECT_CAL_DEF
	#define	COPY_512B_DEF
	#define	FS_WRITE_INTERFACE
	#define	ADD_32_DEF
	
	#define	API_SFC_INTERFACE_WR
#endif


#ifdef	FS_GET_LONG_NAME_DEF
	#define	FS_READ_SECTOR
	#define	SECTOR_REV_DEF
	#define	L_SH16_DEF
	#define	PREV_SECTOR_DEF
	#define	DEC_ADDR_DEF
	#define	NXT_CLST_DEF
	#define	CLST_1_SECT_CAL_DEF
	#define	CAL_ADDRESS
	#define	SUB_32_DEF
	#define	CLST_EXP_DEF
	#define	R_SH32_DEF
	#define	ADD_32_DEF
	#define	PARSE_CLST_2FAT_DEF
	#define FS_FREAD_PREVIOUS_SECTOR_DEF
	#define FS_READ_SECTOR_TO_POINT
#endif


#ifdef	FS_GET_83_NAME_DEF
	#define	FS_READ_SECTOR
	#define	SECTOR_REV_DEF
	#define	L_SH16_DEF
#endif


#ifdef	FS_OPEN_DIR_DEF
	#define	FS_READ_SECTOR
	#define	SRH_FILE
	#define SECTRO_TO_CLUSTER
	#define SUB_32_DEF
	#define CLST_EXP_DEF
	#define	CLST_1_SECT_RD_DEF
	#define	PARSE_ITEM_DEF
	#define	NXT_SECTOR_DEF
	#define	INC_ADDR_DEF
	#define	CLST_1_SECT_CAL_DEF
	#define	PARSE_CLST_2FAT_DEF
	#define	ADD_32_DEF
	#define	R_SH32_DEF
	#define	BEG_CLST_ADDR_DEF
	#define	GET_ITEM_PAR_DEF
#endif


#ifdef	FS_ENTER_DIR_DEF
	#define	ENTER_DIR_DEF
	#define	GET_ITEM_PAR_DEF
	#define	SRH_FILE
	#define SECTRO_TO_CLUSTER
	#define SUB_32_DEF
	#define CLST_EXP_DEF
	#define	FS_READ_SECTOR
	#define	CLST_1_SECT_RD_DEF
	#define	PARSE_ITEM_DEF
	#define	NXT_SECTOR_DEF
	#define	INC_ADDR_DEF
	#define	CLST_1_SECT_CAL_DEF
	#define	PARSE_CLST_2FAT_DEF
	#define	ADD_32_DEF
	#define	R_SH32_DEF
	#define	BEG_CLST_ADDR_DEF
	#define FS_INIT_OPEN_VAR_DEF
#endif


#ifdef FS_GET_FILEPATH_DEF
	#define	MERGE_BYTE_DEF
#endif


#ifdef GET_INTO_SPECIAL_DIR
	#define	FS_ENTER_ROOT_DEF
	#define	ENTER_DIR_DEF
	#define	GET_ITEM_PAR_DEF
	#define	FS_ENTER_DIR_DEF
	#define	SRH_FILE
	#define SECTRO_TO_CLUSTER
	#define SUB_32_DEF
	#define CLST_EXP_DEF
	#define	FS_READ_SECTOR
	#define	CLST_1_SECT_RD_DEF
	#define	PARSE_ITEM_DEF
	#define	NXT_SECTOR_DEF
	#define	INC_ADDR_DEF
	#define	CLST_1_SECT_CAL_DEF
	#define	PARSE_CLST_2FAT_DEF
	#define	ADD_32_DEF
	#define	R_SH32_DEF
	#define	BEG_CLST_ADDR_DEF
#endif


#ifdef FS_GET_VOICE_DIR_DEF
	#define	RECORD_MODULE_DIR
	#define	CLST_1_SECT_RD_DEF
	#define	FS_READ_SECTOR
	#define	PARSE_ITEM_DEF
	#define	VOICE_NAM_CHK_DEF
	#define	NXT_SECTOR_DEF
	#define	INC_ADDR_DEF
	#define	CLST_1_SECT_CAL_DEF
	#define	PARSE_CLST_2FAT_DEF
	#define	ADD_32_DEF
	#define	R_SH32_DEF
	#define	SRH_BLANK_DEF
	#define	SRH_FREE_IN_FAT_DEF
	#define	FAT1_BOUNDARY_CHK_DEF
	#define	FAT_CAL_CLST_DEF
	#define	CHK_CAPACITY_DEF
	#define SUB_32_DEF
	#define	L_SH16_DEF
	#define	R_SH16_DEF
	#define	L_SH32_DEF
	#define	CLST_EXP_DEF
	#define	CHK_DEL_ITEM_DEF
	#define	EXT_ENTRT_FAT_DEF
	#define	CLR_512_DEF
	#define	FS_WRITE_SECTOR
	#define	WR_ENTRY_DEF
	#define	COPY_512B_DEF
	#define	FS_WRITE_INTERFACE
	#define	CLST_2_FAT_DEF
	#define	WR_REC_FAT_DEF

	#define	API_SFC_INTERFACE_WR
#endif


#ifdef	FS_FOPEN_APPOINTED_DEF
	#define	FS_READ_SECTOR
	#define	SRH_FILE
	#define SECTRO_TO_CLUSTER
	#define SUB_32_DEF
	#define CLST_EXP_DEF
	#define	CLST_1_SECT_RD_DEF
	#define	PARSE_ITEM_DEF
	#define	NXT_SECTOR_DEF
	#define	INC_ADDR_DEF
	#define	CLST_1_SECT_CAL_DEF
	#define	PARSE_CLST_2FAT_DEF
	#define	ADD_32_DEF
	#define	R_SH32_DEF
	#define	BEG_CLST_ADDR_DEF
	#define	GET_ITEM_PAR_DEF
	#define FILE_CHK_MODULE
#endif


#ifdef	FS_FOPEN_DEF
	#define	FS_READ_SECTOR
	#define	SRH_FILE
	#define SECTRO_TO_CLUSTER
	#define SUB_32_DEF
	#define CLST_EXP_DEF
	#define	CLST_1_SECT_RD_DEF
	#define	PARSE_ITEM_DEF
	#define	NXT_SECTOR_DEF
	#define	INC_ADDR_DEF
	#define	CLST_1_SECT_CAL_DEF
	#define	PARSE_CLST_2FAT_DEF
	#define	ADD_32_DEF
	#define	R_SH32_DEF
	#define	BEG_CLST_ADDR_DEF
	#define	GET_ITEM_PAR_DEF
#endif


#ifdef	FS_GET_NEXT_FILE_INDIR_DEF
	#define	FILE_CHK_MODULE
	#define	FS_READ_SECTOR
	#define	SRH_FILE
	#define SECTRO_TO_CLUSTER
	#define SUB_32_DEF
	#define CLST_EXP_DEF
	#define	CLST_1_SECT_RD_DEF
	#define	PARSE_ITEM_DEF
	#define	NXT_SECTOR_DEF
	#define	INC_ADDR_DEF
	#define	CLST_1_SECT_CAL_DEF
	#define	PARSE_CLST_2FAT_DEF
	#define	ADD_32_DEF
	#define	R_SH32_DEF
	#define	BEG_CLST_ADDR_DEF
	#define	GET_ITEM_PAR_DEF
#endif


#ifdef	FS_GET_PREVIOUS_FILE_INDIR_DEF
	#define	FILE_CHK_MODULE
	#define	FS_READ_SECTOR
	#define	SRH_FILE
	#define SECTRO_TO_CLUSTER
	#define SUB_32_DEF
	#define CLST_EXP_DEF
	#define	CLST_1_SECT_RD_DEF
	#define	PARSE_ITEM_DEF
	#define	NXT_SECTOR_DEF
	#define	INC_ADDR_DEF
	#define	CLST_1_SECT_CAL_DEF
	#define	PARSE_CLST_2FAT_DEF
	#define	ADD_32_DEF
	#define	R_SH32_DEF
	#define	BEG_CLST_ADDR_DEF
	#define	GET_ITEM_PAR_DEF
#endif


#ifdef	FS_DELETE_DEF
	#define	FS_READ_SECTOR
	#define	FS_WRITE_SECTOR
	#define	L_SH16_DEF
	#define	PREV_SECTOR_DEF
	#define	DEC_ADDR_DEF
	#define	NXT_CLST_DEF
	#define	CLST_1_SECT_CAL_DEF
	#define	CAL_ADDRESS
	#define	SUB_32_DEF
	#define	CLST_EXP_DEF
	#define	R_SH32_DEF
	#define	CLST_2_FAT_DEF
	#define	COPY_512B_DEF
	#define	ADD_32_DEF
	#define	PARSE_CLST_2FAT_DEF
	#define	FS_WRITE_INTERFACE
	#define FS_FREAD_PREVIOUS_SECTOR_DEF
	#define FS_READ_SECTOR_TO_POINT
	#define SECTRO_TO_CLUSTER

	#define	API_SFC_INTERFACE_WR
#endif


#ifdef	FS_FCREATE_DEF
	#define	WR_REC_FAT_DEF
	#define	CLST_1_SECT_RD_DEF
	#define	PARSE_ITEM_DEF
	#define	CHK_DEL_ITEM_DEF
	#define	NXT_SECTOR_DEF
	#define	SRH_BLANK_DEF
	#define	EXT_ENTRT_FAT_DEF
	#define	CLST_1_SECT_CAL_DEF
	#define	CLR_512_DEF
	#define	FS_WRITE_SECTOR
	#define	INC_ADDR_DEF
	#define	CLST_1_SECT_CAL_DEF
	#define	COPY_512B_DEF
	#define	FS_WRITE_INTERFACE
	#define	FS_READ_SECTOR
	#define	PARSE_CLST_2FAT_DEF
	#define	ADD_32_DEF
	#define	R_SH32_DEF
	#define	SRH_FREE_IN_FAT_DEF
	#define	FAT1_BOUNDARY_CHK_DEF
	#define	FAT_CAL_CLST_DEF
	#define	CHK_CAPACITY_DEF
	#define SUB_32_DEF
	#define	L_SH16_DEF
	#define	R_SH16_DEF
	#define	L_SH32_DEF
	#define	CLST_EXP_DEF
	#define	CLST_2_FAT_DEF

	#define	API_SFC_INTERFACE_WR
#endif


#ifdef FS_GET_FREE_SPACE_DEF
	#define SUB_32_DEF
	#define L_SH32_DEF
	#define CLST_EXP_DEF
	#define FAT1_BOUNDARY_CHK_DEF
	#define INC_ADDR_DEF
	#define FS_READ_SECTOR
#endif


#ifdef FS_CHECK_FILE_TYPE
	#define FILE_CHK_MODULE
#endif


#ifdef FS_SEC_TO_CLUSTER_DEF
	#define CLST_EXP_DEF
#endif


#ifdef FS_WRITE_INTERFACE
    	#define API_SFC_INTERFACE_INITPARA
		#define API_SFC_INTERFACE_WR
#endif

#ifdef FS_WRITE_EF_INTERFACE
    	#define API_SFC_INTERFACE_INITPARA
		#define API_SFC_INTERFACE_WR
#endif


#ifdef MSI_SUPPORT_DEF
    	#define MSI_API_DEF
		#define MSI_API_INIT_DEF
		#define MSI_API_READ_SECTOR_DEF
		#define MSI_API_WRITE_SECTOR_DEF
    	#define MSI_DRIVER_DEF
		#define MSI_DRIVER_INIT_DEF
		#define MSI_MAKE_CLOCK_DEF
		#define MSI_DRIVER_READ_SECTOR_DEF
		#define MSI_DRIVER_WRITE_SECTOR_DEF
		#define MSI_CONVERT_ADDR_DEF
		#define MSI_SEL_BUF_DEF
		#define MSI_COMMON_USED_DEF
#endif

#ifdef MSI_INIT_DEF
    	#define MSI_API_DEF
		#define MSI_API_INIT_DEF
		#define MSI_API_READ_SECTOR_DEF
    	#define MSI_DRIVER_DEF
		#define MSI_DRIVER_INIT_DEF
		#define MSI_MAKE_CLOCK_DEF
		#define MSI_DRIVER_READ_SECTOR_DEF
		#define MSI_CONVERT_ADDR_DEF
		#define MSI_SEL_BUF_DEF
		#define MSI_COMMON_USED_DEF
#endif

#ifdef MSI_READ_DEF
    	#define MSI_API_DEF
		#define MSI_API_READ_SECTOR_DEF
    	#define MSI_DRIVER_DEF
		#define MSI_MAKE_CLOCK_DEF
		#define MSI_DRIVER_READ_SECTOR_DEF
		#define MSI_CONVERT_ADDR_DEF
		#define MSI_SEL_BUF_DEF
		#define MSI_COMMON_USED_DEF
#endif

#ifdef MSI_DELFILE_DEF
    	#define MSI_API_DEF
		#define MSI_API_READ_SECTOR_DEF
		#define MSI_API_WRITE_SECTOR_DEF
    	#define MSI_DRIVER_DEF
		#define MSI_MAKE_CLOCK_DEF
		#define MSI_DRIVER_READ_SECTOR_DEF
		#define MSI_DRIVER_WRITE_SECTOR_DEF
		#define MSI_CONVERT_ADDR_DEF
		#define MSI_SEL_BUF_DEF
		#define MSI_COMMON_USED_DEF
#endif

#ifdef MSI_SUPPORT_USB_DEF
		#define MSI_API_DEF
		#define MSI_API_INIT_DEF
		#define MSI_API_MULTI_SEC_DEF
		#define MSI_API_READ_SECTOR_DEF
		#define MSI_API_WRITE_SECTOR_DEF
    	#define MSI_DRIVER_DEF
		#define MSI_DRIVER_INIT_DEF
		#define MSI_MAKE_CLOCK_DEF
		#define MSI_DRIVER_READ_SECTOR_DEF
		#define MSI_DRIVER_WRITE_SECTOR_DEF
		#define MSI_CONVERT_ADDR_DEF
		#define MSI_SEL_BUF_DEF
		#define MSI_COMMON_USED_DEF
#endif


#ifdef __C51__
typedef  unsigned	char	uc8;
typedef  signed     char	sc8;
typedef  unsigned	int 	ui16;
typedef  signed     int		si16;
typedef  unsigned	long	ul32;
typedef  signed     long	sl32;
#endif
